### ISSUE TITLE
Dropdown does not work on mobile on click at the arrow area.

### ISSUE THREAD

**Issue by CmdrMahesh** [fomantic/Fomantic-UI#1668] opened 2020-09-09 09:43 UTC
Hello Buddies,

I have JS fiddle here: https://jsfiddle.net/cmdr_mahesh/5y3tdqom/2/

Tried to test the dropdown action at our website in the mobile and during the test, we found that on click at the arrow area the dropdown does not trigger.

Device simulator at Browserstack:
Samsung Galaxy S6

Problem Area:
![mobile-arrow](https://user-images.githubusercontent.com/46396430/92582551-b4d04200-f2ae-11ea-9423-7f5e542ea9c6.png)

On the desktop environment is works as expected and on the text selection region it works but except at the arrow icon region on the mobile, it fails.

**Comment by lubber-de** [comment] 2020-09-09 14:25
I unfortunately cannot reproduce this. I tried Chrome/Firefox/Samsung Internet via browserstack on every Samsung device down to S6 (as you mentioned) . It works as expected. Clicking (Touching) on the dropdown arrow opens the dropdown list....
Here is a jsfiddle tester for mobile which implements your given jsfiddle. Works also fine on my real Android devices i own (not Samsung)
https://raw.githack.com/lubber-de/fomantic-ui/jsfiddlefullscreen/jsfiddle/#!lubber/51hju4qp/
![s6](https://user-images.githubusercontent.com/18379884/92611316-f4039080-f2b8-11ea-80fe-0e340d50bb7a.gif)

**Comment by lubber-de** [comment] 2020-09-11 11:23
Closing until a reproducable jsfiddle is provided

**Closed by lubber-de** 2020-09-11 11:23 UTC
Labels: state/cannot-reproduce

**Comment by CmdrMahesh** [comment] 2020-09-24 08:02
Extremely sorry @lubber-de for the late respose.

please visit this codepen:

[https://codepen.io/cmdr_mahsh/pen/PoNXdzL](https://codepen.io/cmdr_mahsh/pen/PoNXdzL)

Fomantic UI - 2.8.6

Thank you for your patience.

**Comment by lubber-de** [comment] 2020-09-24 08:29
Well, without using the shadow and/or vue lib it still works for me, so either Vue or the shadow lib seems to modify the click/touch event (?)

**Comment by lubber-de** [comment] 2020-09-24 08:36
🤔 I more think its your shadowRoot usage here which is causing this....(at least on (old) samsung devices)

**Comment by ko2in** [comment] 2020-09-24 10:13
I've different behavior on my Firefox (82) on Ubuntu while testing the code sandbox you provided. The dropdown only works when clicking the arrow. It doesn't work when clicking the other area of the dropdown.

![FUI](https://user-images.githubusercontent.com/930315/94132079-cad02c00-fe84-11ea-95d9-1906b1f1a8fe.gif)

Look like it's causing by ShadowDOM or Vue rather than FUI itself. It's working properly in normal FUI usage.

**Comment by CmdrMahesh** [comment] 2020-09-24 10:22
@ko2in and @lubber-de I confirm that Its Shadow DOM that is causing the issue.
I am using Shadow DOM as the UI is to be rendered over the WordPress CMS based sites and thus it's getting overrun but other UI libraries like jQuery UI and Bootstrap and crashed the initialization routine or altered the look of the components.

**Comment by CmdrMahesh** [comment] 2020-09-24 10:24
Shadow DOM is like a container here that abstracts the outer root container and I think some actions might be delegated through the root and thus the Shadow container's dropdown is not able to initialize properly.
