### ISSUE TITLE
Steps require "active" class in order to show pointer

### ISSUE THREAD

**Issue by utilityboy** [fomantic/Fomantic-UI#830] opened 2019-06-23 18:19 UTC
# Bug Report

Not sure if this is intentional, but steps hide their pointer unless expressly "active".

## Expected result

From Semantic-UI: https://semantic-ui.com/elements/step.html

![image](https://user-images.githubusercontent.com/130537/59980284-a1f62280-95c1-11e9-81b4-59112efd0a03.png)

## Actual result

From Fomantic-UI: https://fomantic-ui.com/elements/step.html

![image](https://user-images.githubusercontent.com/130537/59980296-c6ea9580-95c1-11e9-9521-aae4a91c16b9.png)

## Version
2.7.6

**Comment by lubber-de** [comment] 2019-06-23 19:36
Regression since #216 / 0fa3831be06c04ea6d7a85ca728c8aabbd07d18a
Fixed by #831

**Closed** 2019-07-28 16:13 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, lang: CSS :art:
