### ISSUE TITLE
[Search] Styles not applied on results

### ISSUE THREAD

**Issue by matheusrufca** [fomantic/Fomantic-UI#904] opened 2019-07-25 20:50 UTC
# Styles are not being applied on search results
On search component, the styles are not being applied on search results.
Also the spinner is not being activated during remote query.

## Steps to reproduce
1. Write something on input

## Expected result
Expected the search results with styles

## Actual result
Search results has no style

## Testcase
https://codepen.io/anon/pen/jgMrxB

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/8710641/61907778-8b1a5700-af04-11e9-8e7d-0da240de4c82.png)

## Version
2.7.6

**Comment by matheusrufca** [comment] 2019-07-25 20:56
>index.html
```
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.6/dist/semantic.min.css" />
<title>Hello, world!</title>
</head>
<body>
  <div id="input-search" lass="ui search">
    <div class="ui left icon input">
      <input name="github-search" class="prompt" type="search" placeholder="Search GitHub" />
      <i class="github icon"></i>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.6/dist/semantic.min.js"></script>
  <script src="autocomplete.js"></script>
</body>
</html>
```
>autocomplete.js
```
$('#input-search').search({
	minCharacters: 3,
	maxResults: 10,
	fullTextSearch: true,
	searchOnFocus: false,
	ignoreDiacritics: true,
	sortSelect: 'natural',
	apiSettings: {
		url: '//api.github.com/search/repositories?q={query}'
	},
	fields: {
		results: 'items',
		title: 'name',
		url: 'html_url'
	}
});
```

**Comment by jamessampford** [comment] 2019-07-25 22:07
You’ve made a typo
`<div id="input-search" lass="ui search">`

Should be
` <div id="input-search" class="ui search">`

**Comment by lubber-de** [comment] 2019-07-26 11:43
Confirmed what  @jamessampford  said:
See https://codepen.io/anon/pen/EqgGvM

![image](https://user-images.githubusercontent.com/18379884/61949428-29f98e80-afab-11e9-8a36-a63677aa64f2.png)

Closing, because issue is solved

**Closed by lubber-de** 2019-07-26 11:43 UTC

**Comment by matheusrufca** [comment] 2019-07-30 00:47
Really sorry, totally didn't see that after several tries.
