### ISSUE TITLE
Uncaught TypeError: t[a.value].replace is not a function

### ISSUE THREAD

**Issue by ahmadsyamim** [fomantic/Fomantic-UI#462] opened 2019-02-05 06:33 UTC
# Bug Report

## Steps to reproduce
1. I've migrated from Semantic 2.4
2. Probably from dropdown input. Is there any conflict on that?
ex: 
$('input').dropdown('setup menu', {values:values});
$('input').dropdown('get value');

3. Also i got error on Icon/font-awesome
4.

## Screenshot (when possible)
![]()

## Version
x.x.x

**Comment by lubber-de** [comment] 2019-02-05 11:04
@ahmadsyamim The JS-Error should be fixed by #381. Please update to the latest 2.7.2 which was released today morning and tell us if this fixed your issue with the JS-error. If not, please provide a jsfiddle to reproduce the issue.
If you have another issue with icons, please open a separate issue providing a jsfiddle. Thanks

**Comment by lubber-de** [comment] 2019-02-11 09:56
I am closing this, because the JS Error is reproducable (found) in semantic.min.js of 2.7.1 and fixed in 2.7.2 as mentioned above. If you still have issues using 2.7.2 please provide a jsfiddle. Thanks

**Closed by lubber-de** 2019-02-11 09:56 UTC
Labels: needs more info
