### ISSUE TITLE
Unable to create labeled button with label on both sides

### ISSUE THREAD

**Issue by nektro** [fomantic/Fomantic-UI#789] opened 2019-05-31 22:12 UTC
# Bug Report

In regards to https://fomantic-ui.com/elements/button.html#labeled

## Steps to reproduce
```html
<div class="ui labeled button">
    <div class="ui icon button"><i class="minus icon"></i></div>
    <div class="ui basic label">2,048</div>
    <div class="ui icon button"><i class="plus icon"></i></div>
</div>
```

## Expected result
The label is able to have a `left` and `right` button and look flush.

## Actual result
Label only flushes itself with either the left or right side.

## Testcase
see: Steps to reproduce

## Screenshot (when possible)
![](https://media.discordapp.net/attachments/423451436303515648/584138495652790331/unknown.png)

## Version
2.7.5

**Comment by apple-idn** [comment] 2019-06-02 15:27
Button groups can show groups of icons
try https://jsfiddle.net/allwe/kj8sdox4/2/

**Comment by apple-idn** [comment] 2019-06-02 15:30
Button groups can show groups of icons
try https://jsfiddle.net/allwe/kj8sdox4/15/

**Comment by nektro** [comment] 2019-06-02 16:58
@apple-idn while visually this works, functionally it does not because I want the center item to be a `ui basic label` not a `ui basic label button`.

**Comment by lubber-de** [comment] 2019-06-03 06:23
Duplicate of #536

**Closed** 2019-06-03 16:56 UTC
Labels: :paperclip: duplicate, :zap: enhancement, lang: CSS :art:
