### ISSUE TITLE
Fomantic UI installation issue

### ISSUE THREAD

**Issue by hayleyesthertaylor** [fomantic/Fomantic-UI#1990] opened 2021-06-18 11:18 UTC
Trying to install Fomantic UI for a HTML project, as I couldn't get Semantic UI to install on Gulp V4. But now when I try installing Fomantic UI I get this error. Does anyone have any idea how I can fix it? Thanks.

```(base) Hayleys-MacBook-Air:czechmate hayleytaylor$ npm install fomantic-ui
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! path /Users/hayleytaylor/Documents/czechmate/node_modules/fomantic-ui
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c gulp install
npm ERR! [12:04:11] Using gulpfile ~/Documents/czechmate/node_modules/fomantic-ui/gulpfile.js
npm ERR! [12:04:11] Starting 'install'...
npm ERR! 
[12:04:11] Starting 'run setup'...
npm ERR! ? Set-up Semantic UI (Use arrow keys)
npm ERR! ❯ Automatic (Use default locations and all components) 
npm ERR!   Express (Set components and output folder) 
npm ERR!   Custom (Customize all src/dist values) [12:04:11] The following tasks did not complete: install, run setup
npm ERR! [12:04:11] Did you forget to signal async completion?
```

this is the version of gulp I am using...
```(base) Hayleys-MacBook-Air:czechmate hayleytaylor$ gulp --version
CLI version: 2.3.0
Local version: 4.0.2
(base) Hayleys-MacBook-Air:czechmate hayleytaylor$ 
```

**Comment by lubber-de** [comment] 2021-06-18 11:41
Duplicate of #1911 

Please try
```
npm install --ignore-scripts fomantic-ui
cd node_modules/fomantic-ui
npx gulp install
npx gulp build
```

**Closed by lubber-de** 2021-06-18 11:41 UTC
Labels: state/awaiting-investigation, state/awaiting-triage, type/bug
