### ISSUE TITLE
[Calendar] 'set date' behavior set previous day

### ISSUE THREAD

**Issue by aldebaran798** [fomantic/Fomantic-UI#935] opened 2019-08-14 00:02 UTC
# Bug Report

## Steps to reproduce
1. Use 'set date' behavior with any date

## Expected result
Input text with asigned date value

## Actual result
Input text with previous day to asigned date value

## Testcase
https://jsfiddle.net/badwin/n0z7vbrf/3/

## Version
2.7.7

**Comment by aldebaran798** [comment] 2019-08-14 00:51
Is related with ISO string formatting?
https://github.com/mdehoog/Semantic-UI-Calendar/issues/87

I'm updating from semantic ui and sending a text string works.

**Comment by lubber-de** [comment] 2019-08-14 11:01
I unfortunately cannot reproduce. The jsfiddle correcly displays the date, wou are providing.
![image](https://user-images.githubusercontent.com/18379884/63016036-e0f27700-be92-11e9-9045-1b5d5b92d894.png)
Beyond the code the calendar tries to parse the given date string via `new Date('2019-08-13')`, which works correctly for me.
I guess it's because of the timezone where you are living/working.
Please try if `2019-08-13T00:00:00` works for you here https://jsfiddle.net/0s4x2qd1/

**Comment by aldebaran798** [comment] 2019-08-14 14:22
My time zone is UTC-5

When i try with the jsfiddle that i share this is the result

![2](https://user-images.githubusercontent.com/19268443/63028495-8f3af400-be74-11e9-8ddc-f1847a20611f.png)

The result with the jsfiddle that you share this is the result

![2previewFomantic](https://user-images.githubusercontent.com/19268443/63028617-c6110a00-be74-11e9-8479-7f3cb9fad011.png)

**Comment by lubber-de** [comment] 2019-08-14 15:07
😲 Very strange. Which browser/version/os are you using? 
The date calculation is done by your local javascript 'new Date()' (equivalent to `Date.parse()`) and until ES5 implemented differently in different browsers it seems.
Again, i still cannot reproduce, it all works in my local browsers (IE/Edge/FF/Chrome) and i am UTC+1

Please try any of these, (all of them still work correctly for me unfortunately :( )
- `'2018/08/13'`
- `'2018 August, 13'`
- `'13-08-2018'`
- `'13.08.2018'`

The safest way should definately work:
- `new Date(2018,7,13)`

**Comment by lubber-de** [comment] 2019-08-14 15:10
May help to understand the different results
https://stackoverflow.com/questions/2587345/why-does-date-parse-give-incorrect-results

**Comment by aldebaran798** [comment] 2019-08-14 18:19
I'm using Chrome V. 76.0.3809.100 and Firefox V. 68.0.2

All the alternatives works fine, only YYYY-MM-DD dates are failing for me

**Comment by lubber-de** [comment] 2019-08-14 19:07
Alright, will close this issue then.

**Closed by lubber-de** 2019-08-14 19:08 UTC
Labels: :thinking: cannot reproduce

**Comment by Druidsnake** [comment] 2019-09-25 05:23
i have same issue
im using vivaldi browser,  GMT -5 with YYYY-MM-DD format string i got date-1day. but when add: + "T00:00:00" it works again correctly.
thx

**Comment by lubber-de** [comment] 2019-09-25 05:26
@Druidsnake that's most probably because of your local timezone. In the end the string date is given to the js engine to produce a js date object which then does not know about the timezone until you are providing it as mentioned by you.
