### ISSUE TITLE
[Dropdown] Search with remote content causes Firefox to hang

### ISSUE THREAD

**Issue by gdembowski** [fomantic/Fomantic-UI#2971] opened 2024-01-06 10:34 UTC
# Bug Report
I have noticed strange behaviour in the Firefox browser version 121 and higher. The browser hangs when searching remote from API. Strangely enough, not all sources are causing the problem.

## Steps to reproduce
It can be reproduced on the current docs
1. Open Firefox
2. Go to: https://fomantic-ui.com/modules/dropdown.html#sanitized-version
3. Start typing in "Sanitized Version" dropdown

## Expected result
I expect the list to be filtered.

## Actual result
The page is actually frozen under Firefox and surprisingly this filtering doesn't work in other browsers.
On the other hand the other examples with remote content works fine, e.g.: https://fomantic-ui.com/modules/dropdown.html#match-search-query-on-server

## Testcase
https://fomantic-ui.com/modules/dropdown.html#sanitized-version  

## Screenshot (if possible)
![Screenshot 2024-01-06 at 11 24 28](https://github.com/fomantic/Fomantic-UI/assets/2320282/d152d134-5316-41e1-b7e1-85bca25a0632)
![Screenshot 2024-01-06 at 11 28 09](https://github.com/fomantic/Fomantic-UI/assets/2320282/820112cd-4bdd-48a1-bee0-ad0fa489a767)

## Version
Fomantic ver 2.9.3  
Firefox 121

**Comment by gdembowski** [comment] 2024-01-07 11:13
Thanks @lubber-de for the clarification. Indeed, the freezing Firefox is the main problem. I just panicked a bit and thought the lack of filtering is a related issue, but you're right, that's not the case with the static JSON example.  
  
I did another investigation and it seems the number of records returned by the API matters.
Here are the examples:
1. Static content 333 records: no freezing - https://jsfiddle.net/t028c5L7/1/
2. API content 329 records: freezing for a long time - https://jsfiddle.net/5kvwe47o/
3. API content 158 records: short freezing - https://jsfiddle.net/b5yc48g7/1/
4. API content 67 records: unnoticeable, small delay in typing - https://jsfiddle.net/02jorq79/1/

**Comment by prudho** [comment] 2024-01-09 14:09
@slachinger indeed, it helps !

Looks like it's a CSS issue with Firefox 121.x+, but i cannot figure what's happening here.

In [`dist/fomantic.css L43527`](https://github.com/fomantic/Fomantic-UI/blob/a8681bfc1ff225ddd071d8ccda148e0f522934ce/dist/semantic.css#L43527), just comment this lines:

```css
@supports selector(:has(.f)) {
  *:has(> .ui.piled.segment) {
    z-index: 0;
    position: relative;
  }
}
```

And freezes are gone !

@lubber-de I suspect this to be the culprit, but why it's driving Firefox nuts is out of my knowledge !

**Comment by lubber-de** [comment] 2024-01-09 17:30
Thanks for finding the reason @prudho !
Well, Firefox just supported `:has` [since 121](https://caniuse.com/?search=%3Ahas) which is obviously implemented ineffectively in firefox which causes the freeze so mozilla has to fix this in general.

What one can do right now:

- set `@variationSegmentPiled: false` which will remove the piled segment variant

What we can change in the core is either

- adjust the `@supports` selector for the moment so it won't affect firefox (espcially since 121 where `:has` support is enabled by default)
```diff
- @supports selector(:has(.f)) {
+ @supports selector(:has(.f)) and (not(-moz-appearance: none)) {
```
  This could be removed again once it is fixed in firefox
- make the `*:has` selector more specific, so it won't affect dropdown (infact a piled segment will most probably never be inside a dropdown), but this drastically limits the usage, as one has to declare a possible `piled segment` to a prepared parent element (and i dont imagine what we should define here, that was the reason back then to use the star selector)
 However, i haven't yet tested if this will fix it at all in firefox as it seems the firefox css engine will check the selector on each DOM change, so this probably doesnt help at all.
- Partly revert #2730 and remove the whole selector (which i dont think we should do as other browsers support this just fine without a performance lag)

What do you guys prefer? ( i vote for the first option to advance the `@supports` selector

**Comment by prudho** [comment] 2024-01-10 08:03
I choose first option too. It's quick and just disable a buggy behavior without breaking anything else.

**Comment by lubber-de** [comment] 2024-01-10 18:27
mmh, i cannot get this to reprocuce locally or via a jsfiddle and not even by trying the docs locally. Firefox works just fine.
ONLY the online docs freeze.
Even worse, i tried to manipulate the css inside the online docs as discussed above and _it still freezes_.
I also tried to make the :has selector more specific (even by using a non existing selector) ...and it still freezes.

@prudho  Have you got a reproducable jsfiddle or how did you confirm removing the `@supports` selector worked for the online docs?

https://jsfiddle.net/lubber/etpjsrxo/6/

**Comment by lubber-de** [comment] 2024-01-10 18:32
Here a comparison between local docs `yarn docpad run` -> no freeze
and fomantic-ui.com -> freeze, although the docs are the same code

![firefoxfreezeonline](https://github.com/fomantic/Fomantic-UI/assets/18379884/c282a1d8-bd21-46bf-9e64-ecaaffc685aa)

**Comment by lubber-de** [comment] 2024-01-10 18:39
Here is my try to change the supports-selector as discussed above (i added a red background to find if the additional rule will not affect firefox)...it still freezes although the selector is not even executed. 

So, even if we add my suggested change "dry" to the core, i suspect the issue still exists. 

![firefoxfreezeonlineselectorchange](https://github.com/fomantic/Fomantic-UI/assets/18379884/33d229ce-bdb7-4c89-bd21-e3c5efbe8184)

**Comment by lubber-de** [comment] 2024-01-10 18:44
And, even weird....last try: I removed the whole selector...firefox still freezes

@prudho Please help if/where/how you confirmed it is fixed when removing the selector
![firefoxfreezeonlineselectorremove](https://github.com/fomantic/Fomantic-UI/assets/18379884/8ffcaf60-d75c-4d62-b220-32c2bcf06e94)

**Comment by lubber-de** [comment] 2024-01-10 20:19
@slachinger @prudho 
🤔 I took the working example using 2.9.1 and added the `@supports` selector.

https://jsfiddle.net/e70xjovw/1/

I would have expected firefox to freeze now.... but it doesnt (which would explain, why my previous teste also did not make any difference

So the reason  for the freze must be someehere else

**Comment by lubber-de** [comment] 2024-01-10 20:57
I got it. 💪🏼  It's a combination of 3 specific `@supports selector(:has)` selectors , so `:has` is still broken in certain scenarios in firefox.
Using 2.9.2 and adding the 3 selectors in question will freeze firefox reproducable.
https://jsfiddle.net/e70xjovw/8/

adjusting the selector to ignore firefox will fix it in firefox
https://jsfiddle.net/e70xjovw/9/

Howerever: keep in mind that the selectors in question do not even belong to the example code! There is no piled segment and no pointing dropdown so the selector will not even trigger. (and i also tested to make the `*:has` more specific: It does not matter. Something in firefox makes the parsing of those three internally freeze....

Will prepare a PR :)

**Comment by lubber-de** [comment] 2024-01-10 21:10
Fixed by #2973

**Comment by lubber-de** [comment] 2024-01-10 21:27
I filed an issue for mozilla at https://github.com/webcompat/web-bugs/issues/132131

**Comment by lubber-de** [comment] 2024-01-11 13:02
mozilla confirmed the issue and takes care about that by https://bugzilla.mozilla.org/show_bug.cgi?id=1874066

**Comment by lubber-de** [comment] 2024-01-20 19:13
I can confirm, the issue is fixed in latest firefox 123.a01
https://archive.mozilla.org/pub/firefox/nightly/2024/01/2024-01-20-09-39-31-mozilla-central/

**Comment by lubber-de** [comment] 2024-02-20 18:59
Firefox 123 was released today and fixed the issue. Please update your browser

**Closed by lubber-de** 2024-02-20 18:59 UTC
Labels: type/bug, browser/firefox, state/has-pr
