### ISSUE TITLE
[scope] summary of your bug

### ISSUE THREAD

**Issue by ashishemptyops** [fomantic/Fomantic-UI#2563] opened 2022-11-19 13:34 UTC
# Bug Report
We are facing a strange issue with the slider. The strange part is there it is working on many sites but it stopped working recently on 2 different sites. The error is related to slider data wherein it is unable to find the range property in an object. I have pasted the exact error below.
Uncaught TypeError: Cannot read properties of undefined (reading 'range') 

## Steps to reproduce
1. Please go to this link "https://thediamondart.com/product-category/engagement-ring/?EO_WBC=1&BEGIN=engagement-ring&STEP=1&FIRST&SECOND"
2. Open the console.
3. Lock at this error: Uncaught TypeError: Cannot read properties of undefined (reading 'range') -> "return $module.hasClass(settings.className.range);"

## Expected result
Range Slider Work

## Actual result
The range Slider is not working

## Version
2.8.6

**Comment by lubber-de** [comment] 2022-11-19 14:51
As far as i can tell from your website you are messing up with the `$.fn.slider` function by overriding and replacing it at several places, 
![image](https://user-images.githubusercontent.com/18379884/202856693-e31764b6-df99-4fb4-8060-987e99d40ff8.png)
which i cannot really follow without deeply debugging your website code, which i won't.

You also have much more issues as you also  seem to reference jquery flexslider and masonry, which are not properly loaded as well. 
![image](https://user-images.githubusercontent.com/18379884/202856633-c3819f51-3028-4b35-9e90-c4c4fec850b7.png)

In the end the `settings` are not complete anymore, missing the whole "className" values and thus `settings.className.range` does not exist anymore, but it is expected. Somewhere the settings are completey overridden which i could not figure out quickly from the dev console.

Please provide a reproducable simple jsfiddle, because we don't time to debug your whole website. Thanks.
Try to not replace the `.fn.slider` at runtime.

I am closing this until you can provide a above mentioned reproducable jsfiddle using the default FUI codebase.

**Closed by lubber-de** 2022-11-19 14:51 UTC
Labels: type/bug, state/awaiting-investigation, state/awaiting-triage

**Comment by ashishemptyops** [comment] 2022-11-22 13:41
Ok, Thanks for providing the details. I acknowledge that we had some tweaks around the slider behavior but it is working for a long time right now on many different sites. I am providing the link to one such site below where it is working.

https://dazzlediamondslondon.co.uk/product-category/eo_diamond_shape_cat/?EO_WBC=1&BEGIN=eo_diamond_shape_cat&STEP=1&FIRST&SECOND

Let me know if I should open a new bug then I will do so.
