### ISSUE TITLE
Progress: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#734] opened 2019-05-09 09:50 UTC
Hello,
in my Angular web app I have upgraded Semantic-UI from version 2.4.2 to Fomantic-UI 2.7.4.

Now, when I use progress module with something like this:

`$(this._progress.nativeElement).progress('get percent')`

I get the following error:

```
ERROR TypeError: Cannot read property '0' of undefined
    at HTMLDivElement.percent (semantic.min.js:11)
    at Object.invoke (semantic.min.js:11)
    at HTMLDivElement.<anonymous> (semantic.min.js:11)
...
```

In other cases if I use progress like this:

```
<div class="ui tiny green progress">
    <div class="bar" [style.width]="file.percent + '%'"></div>
</div>
```

I have no errors in console, but the progress bar doesn't start or get filled like before upgrade.

For the first case I solved changing Fomantic-UI **progress.js** source file in the following way:

```
percent: function(index) {
  return module.percent ? module.percent[index || 0] || 0 : 0;
},
value: function(index) {
  return module.nextValue || module.value ? module.value[index || 0] || 0 : 0;
}
```
But this doesn't do the trick for the second case as well.

What could I fix this?

**Comment by lubber-de** [comment] 2019-05-09 10:17
The TypeError is a duplicate of #719 and fixed by #706 in the upcoming 2.7.5

For the other question: How does the JS code look like to initiate the second mentioned progress-bar? 
You either have to provide the percentage values via JS setting or as data attributes. 
Could you please provide a jsfiddle to reproduce the issue?

**Comment by smartm0use** [comment] 2019-05-09 10:54
Providing you a jsfiddle is quite hard for me because I can't replicate my code in an easy way.
Anyway I find out that if I replace `progress.less` file with the one of Semantic-UI 2.4.2, it works again.

Could this hint helpful for you?

**Comment by lubber-de** [comment] 2019-05-09 11:35
Could you at least provide the js code which is instantiating the mentioned progress?
As your HTML example does not provide a `data-percent` attribute, your JS snippet must look like this

```javascript
$('.ui.progress').progress({
	percent:80
})
```
which works as expected with the current codebase of 2.7.4
See https://jsfiddle.net/m2r5yd1u/

**Comment by lubber-de** [comment] 2019-05-09 11:38
Also
```
$('.ui.progress').progress('set percent',50);
```
works fine
See  https://jsfiddle.net/m2r5yd1u/1/

**Comment by smartm0use** [comment] 2019-05-09 12:24
Double checking it I see that I have no JS, anyway it worked with 2.4.2.
I see that with `progress.less` of 2.7.4 there are these rules:

```
.ui.ui.ui.progress:not([data-percent]) .bar,
.ui.ui.ui.progress[data-percent="0"] .bar {
  background:transparent;
}
```

So in my case the progress bar doesn't get filled.

Then I added the JS snippet to make it working, because if I use `data-percent` I get an error about unrecognized tag for a div element.

**Comment by lubber-de** [comment] 2019-05-09 12:42
I see. The mentioned additional code was implemented to not display any progress when the bar is actually 0% (or nothing). Before that, even a 0% progress had a minimum width. That was a logical wrong behavior, which we corrected. 

In 2.7.5 there will be another fix #625 , which makes sure at least the background bar (remaining progress width) is shown again.

So, if you really would like to show a progress, you have to provide a percentage of > 0.

**Comment by smartm0use** [comment] 2019-05-09 12:57
Ok, I see. The weird thing is that with Semantic-UI 2.4.2 I can see progress bar get filled without any JS snippet, just `[style.width]="file.percent + '%'"` bind to `file.percent` that changes dinamically.

**Comment by lubber-de** [comment] 2019-05-09 14:10
@smartm0use 
Ok, here's a proposal: If you add the static property `data-percent` (without any binding) to the progress element, then your approach, by changing the inline style widthvia Angular binding, also works with FUI 2.7.4+ (without JS instantiation through FUI)
Please try 
```html
<div class="ui tiny green progress" data-percent>
    <div class="bar" [style.width]="file.percent + '%'"></div>
</div>
```
with FUI 2.7.4

See https://jsfiddle.net/jcgybd9m/

**Comment by smartm0use** [comment] 2019-05-10 08:03
Yes, it worked, thank you!

**Closed** 2019-05-16 08:28 UTC
Labels: :heavy_check_mark: next release, :paperclip: duplicate, :thought_balloon: usage question, wontfix
