### ISSUE TITLE
Widgets are inaccessible to screen readers

### ISSUE THREAD

**Issue by Jookia** [fomantic/Fomantic-UI#2019] opened 2021-07-19 10:26 UTC
# Bug Report
You can't use most widgets with a screen reader.

## Steps to reproduce
1. Open a screen reader
2. Try to use a dropdown

## Expected result
The dropdown should read elements as I use them and lock focus.

## Actual result
Nothing is read, focus is mismanaged.

## Version
any

**Comment by lubber-de** [comment] 2021-07-19 10:32
Duplicate of #1332

**Closed by lubber-de** 2021-07-19 10:32 UTC
Labels: state/awaiting-investigation, state/awaiting-triage, type/bug
