### ISSUE TITLE
[Progress] Bar wrapper disappears at 0%

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#691] opened 2019-04-23 21:35 UTC
# Bug Report

## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/progress.html
2. Pick any progress bar and use the minus button to remove progress
3. Bar wrappers (grey background) disappear at 0 (they do however reappear when incrementing)

## Expected result
An empty bar should be visible (added benefit of the below content also not moving as a result)

## Actual result
Nothing is visible (the “sizes” group labels go a bit weird too if you see)

## Version
2.7.3

**Comment by lubber-de** [comment] 2019-04-23 21:41
Fixed by #625

**Comment by lubber-de** [comment] 2019-04-23 21:43
Duplicate of #624
Fixed by #625

**Closed** 2019-05-16 08:29 UTC
Labels: :bug: confirmed bug, :paperclip: duplicate
