### ISSUE TITLE
[Dropdown Multiple Search] Error when zero options set

### ISSUE THREAD

**Issue by noneymous** [fomantic/Fomantic-UI#1726] opened 2020-10-26 09:46 UTC
# Bug Report
Dropdown runs into "**Uncaught TypeError: e.html() is undefined**" error under certain circumstances:
- Dropdown with **multiple search** selection
- Empty initial array of possible options
- The error happens after leaving the input box

The error doesn't seem to have an effect **in my use case**, but it shouldn't be there. It might break onchange actions, or something...

## Steps to reproduce
1. Initialize multiple search box dropdown with an empty list of options
2. Click into the input search box
3. Click outside the input search box, to leave the dropdown item
4. Check developer console for error

## Expected result
Nothing should happen

## Actual result
Error is triggered. Although, functionality doesn't seem to be affected.

## Screenshot (if possible)
![grafik](https://user-images.githubusercontent.com/31357019/97156748-6d771580-1777-11eb-8512-f5cf49142f35.png)

## Version

2.8.7 (latest version), did work in 2.7.8

**Comment by noneymous** [comment] 2020-10-26 10:00
The error seems to happen in combination with `forceSelection=true` (default). After changing `forceSelection` to _false_, the error is not triggered anymore.

This mitigates the bug for me, because I actually prefer `forceSelect=false`. However, other developers might not...

**Comment by ko2in** [comment] 2020-10-26 10:27
@noneymous I guess this has already fixed in this [PR#1681](https://github.com/fomantic/Fomantic-UI/pull/1681)

Can you check with @TheJltres fiddle and confirm that it works for you too?

**Comment by lubber-de** [comment] 2020-10-26 20:10
@noneymous I also think this should be fixed  already as @ko2in pointed out.
However, i am not able to reproduce this behavior from your mentioned steps.
Please adjust the following jsfiddle so it triggers the error 
http://jsfiddle.net/lubber/9qxh783e/3/

**Comment by lubber-de** [comment] 2020-11-03 08:28
Closing because of no more response and almost already fixed as mentioned above.

**Closed by lubber-de** 2020-11-03 08:28 UTC
Labels: needs-more-info, state/cannot-reproduce, type/bug, type/duplicate
