### ISSUE TITLE
icon menu creates TypeErrors when hovering fast between entries

### ISSUE THREAD

**Issue by bbernhard** [fomantic/Fomantic-UI#804] opened 2019-06-10 12:16 UTC
# Bug Report

## Steps to reproduce
1. Create a icon menu with menu entries that have tooltips
2. Hover fast over the individual menu entries

## Expected result
There shouldn't be any errors

## Actual result
There are a lot of TypeErrors generated 

## Testcase
https://jsfiddle.net/mv2aferh/1/

## Screenshot
![Selection_011](https://user-images.githubusercontent.com/5710631/59194718-3906b780-8b8a-11e9-98ef-89f6a9bbe517.png)

## Version
2.7.5

**Comment by lubber-de** [comment] 2019-06-10 14:23
Duplicate of #747
Fixed by #748

See your adjusted jsfiddle here https://jsfiddle.net/L6qtapsm/

**Closed** 2019-06-16 19:52 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :paperclip: duplicate, lang: JavaScript :scroll:
