### ISSUE TITLE
Animated button not fit inside the Accordion

### ISSUE THREAD

**Issue by hajanajubudeen88** [fomantic/Fomantic-UI#2278] opened 2022-03-24 12:09 UTC
# Bug Report
In the TestCase, I'm facing some button size issue 

## Steps to reproduce
1. I'm using animation button in two places one is in the top of the page and another is in inside the accordion 
2. The top buttons are working good 
3. But once the same code i use inside the accordion the sizes may differ from outside the accordion
(NOTE : Only Animated buttons not fit inside the accordion, normal buttons working good )

## Expected result
Need the same size both inside the accordion and out side the accordion

## Fiddle Link
https://jsfiddle.net/hajanajubudeen88/u4bzjqmt/14/

## Screenshot (if possible)
![error](https://user-images.githubusercontent.com/32840808/159913189-7102dd1c-4001-412d-a97b-4f0ffc0e0491.jpg)

## Version

2.x.x

**Comment by lubber-de** [comment] 2022-03-24 12:20
Pleae provide a jsfiddle for easier investigation. Thanks

**Comment by lubber-de** [comment] 2022-03-24 12:24
Cannot reproduce: Here is a jsfiddle having an accordion including animated buttons. All looks normal to me.
Please adjust the jsfiddle so your issue is reproducable
https://jsfiddle.net/lubber/se1qa8Lj/4/

**Comment by hajanajubudeen88** [comment] 2022-03-24 13:45
Thank You for your response appreciated, Kindly check the jsfiddle : https://jsfiddle.net/hajanajubudeen88/u4bzjqmt/14/

**Comment by lubber-de** [comment] 2022-03-24 14:26
Thanks. Your issue has been fixed in the night 2.9.0 beta by #2197 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/gpfu54b2/

**Comment by hajanajubudeen88** [comment] 2022-03-25 10:32
> Thanks. Your issue has been fixed in the nightly 2.9.0 beta by #2197 See your adjusted jsfiddle here https://jsfiddle.net/lubber/gpfu54b2/

This works only in jsfiddle, once i use this code into my project its not working (facing the same issue), Thanks

**Comment by lubber-de** [comment] 2022-03-25 11:02
Because you probably did not use the nightly beta in your code which is available at the cdn via `https://cdn.jsdelivr.net/npm/fomantic-ui@nightly/dist/semantic.min.css` and https://cdn.jsdelivr.net/npm/fomantic-ui@nightly/dist/semantic.min.js

Take a look at the ja fiddle to the left where the resources are listed.

**Closed** 2022-10-10 05:52 UTC
Labels: type/bug
