### ISSUE TITLE
Slider - "unable to preventDefault..." under Chrome emulating mobile devices

### ISSUE THREAD

**Issue by qroft** [fomantic/Fomantic-UI#1702] opened 2020-10-10 09:38 UTC
# Bug Report
I am using the slider as range and Chrome shows me this alert in the console:
**[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080**

I googled it and understood Google's intention here. The question is: can this be ignored for Fomantic or will it be fixed in the future?

## Steps to reproduce
1. Create the slider as range with an input field to show the values.
2. Load your page and check the console.

## Expected result
No error in console.

## Actual result
Slider works, though at the moment i can not see the values in my input field. As mentioned above, error pops up in the console.

## Version
2.8

**Comment by lubber-de** [comment] 2020-10-10 11:43
Could you please adjust the following jsfiddle, because i am not able to reproduce this with current chrome 😢 
See https://jsfiddle.net/lubber/rtd3ycp8/4/

![sliderconsole](https://user-images.githubusercontent.com/18379884/95654183-956f4380-0afe-11eb-8beb-764a98070238.gif)

**Comment by lubber-de** [comment] 2020-10-17 15:51
Closing until reproducable jsfiddle is provided

**Comment by alexjv89** [comment] 2021-01-15 11:48
Not able to reproduce the issue in js fiddle. For me this issue happens particularly on mobile. Chrome mobile device shows the same error. 

Steps to reproduce 
- go to https://fomantic-ui.com/modules/slider.html
- Toggle device to mobile in chrome console
- refresh the page
- Try moving the slider

![image](https://user-images.githubusercontent.com/2733923/104723425-3e0fed80-5755-11eb-9041-7c845f5c75aa.png)

**Comment by lubber-de** [comment] 2021-01-17 17:51
@alexjv89 While i can reproduce the behavior using developer tools and switching to mobile view, i still cannot reproduce this on real mobile devices. The slider is working fine on Android and iOS as far as i can tell.

So, we have to hunt for a bug only for desktop browsers trying to emulate touchstart/touchmove in certain situations . (btw. when just tapping (not dragging) somwhere else on the slider it's still working.

My above mentioned jsfiddle can be tested on mobile via https://fomantic-ui.com/jsfiddle/#!lubber/rtd3ycp8/4

However, I reopen this

**Comment by alexjv89** [comment] 2021-01-18 01:27
I was on v2.7.8 on which the slider was failing to move on mobile(& on chrome emulating mobile devices). Upgraded to v2.8.6 - The console error still shows but the slider functionality works fine. 

This is where I am using the slider - https://mralbert.in/pricing

**Closed** 2022-11-17 12:58 UTC
Labels: type/bug, lang/javascript, device/computer, device/mobile, state/awaiting-investigation
