### ISSUE TITLE
[Form] checkbox doesn't respect form size

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#666] opened 2019-04-12 09:13 UTC
# [Form] checkbox doesn't respect form size

## Steps to reproduce
1. Define a .ui.form of a given size, ex.: .ui.tiny.form
2. Add an input and a checkbox to the form

## Expected result

All fields inside the form should inherit their font-size from the size variation of the parent form itself

## Actual result

It works for input fields but not for checkboxes

## Testcase

https://jsfiddle.net/a1sxk7du/

## Version

2.7.4

**Comment by exoego** [comment] 2019-04-12 10:56
Confirmed.

❌ checkbox
✔️ input
✔️ textarea
✔️ dropdown (select)
✔️ message

Only checkbox does not respect the size of parent form.

**Comment by lubber-de** [comment] 2019-04-12 13:19
Related SUI issue: https://github.com/Semantic-Org/Semantic-UI/issues/3941
Jack said, it is using px instead of em because of rounding issues... 🤔 Could not really reproduce in a short test.
Anyway, leaving the checkbox as it is (by 17px width/height) and adjust by `transform:scale()` seems to easily do the job without dealing with top-margins (which would be necessary if done only via width/height adjustments) Just by scaling, the checkbox always stays centered to the label text...
Here is some testing: https://jsfiddle.net/mygbzvfc/

**Comment by lubber-de** [comment] 2019-07-19 22:23
Fixed by https://github.com/fomantic/Fomantic-UI/pull/886
See your adjusted jsfiddle here: https://jsfiddle.net/vkjzudc6/

**Closed** 2019-07-28 16:13 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :sleeping: sui issue, lang: CSS :art:
