### ISSUE TITLE
[Segment] secondary segment per default black colored

### ISSUE THREAD

**Issue by j5k** [fomantic/Fomantic-UI#407] opened 2019-01-17 13:14 UTC
# Bug Report

## Steps to reproduce
1. go to fiddle
2. see secondary segment colored black
3. in 2.6.3 it was still correct

## Testcase
https://jsfiddle.net/qfzjhn59/

## Version
2.7.1

**Comment by hammy2899** [comment] 2019-01-17 13:53
Duplicate of #364

**Closed by hammy2899** 2019-01-17 13:53 UTC
Labels: :paperclip: duplicate
