### ISSUE TITLE
[Accordion] browser warning `downloadable font: OS/2: Bad sTypoLineGap...`

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2478] opened 2022-10-03 06:41 UTC
# Bug Report

## Steps to reproduce
1. open https://ui.agiletoolkit.org/demos/interactive/accordion.php (also reproducible on docs https://fomantic-ui.com/ homepage)
2. notice
   ![image](https://user-images.githubusercontent.com/2228672/193515340-7e1d4c8d-5999-4f28-b055-8326cb913630.png)
   in the browser console

tested with the latest Fomantic-UI beta and the problem is still present

browser: Firefox

reported also in https://github.com/Semantic-Org/Semantic-UI/issues/2146

I checked the browser console also for the Fomantic-UI docs and on https://fomantic-ui.com/modules/rating.html page (and many others) I found:

![image](https://user-images.githubusercontent.com/2228672/193516370-22d76be2-abaf-4e03-b22f-b7165c777ab5.png)

![image](https://user-images.githubusercontent.com/2228672/193516475-f994ec35-1428-463a-b86b-e71fd9ec4ac1.png)

(probably doc unwanted log only)

in https://fomantic-ui.com/behaviors/visibility.html

![image](https://user-images.githubusercontent.com/2228672/193516736-a75f2197-e4e0-48be-b745-57e9ff97e2b1.png)

(not exactly sure if these errors are expected)

in https://fomantic-ui.com/modules/sticky.html

![image](https://user-images.githubusercontent.com/2228672/193516850-fa980bcf-7f48-48f0-9720-c8e634a19a44.png)

link https://fomantic-ui.com/modules/dropdown.html#multiple-select-settings with fragment is not working - not navigating to the target position

**Comment by mvorisek** [comment] 2022-10-03 07:33
there are 4 inlined fonts - `Step`, `Accordion`, `Checkbox`, `Dropdown`

the problem is only with `Accordion` and `Dropdown` fonts\* and only `truetype` type, when `truetype` type is removed, the problem is gone - https://jsfiddle.net/1uj4r7t3/1/

https://fomantic-ui.com/elements/step.html - there is also simillar problem in the docs with `Docs Code` font

\* checked on pages where each font is really used, otherwise there is no console error at all

**Comment by lubber-de** [comment] 2022-10-03 07:38
Duplicate of #1254

**Comment by lubber-de** [comment] 2022-10-03 07:55
I'll remove the truetype entries. Thanks for figuring this out!

**Comment by lubber-de** [comment] 2022-10-03 08:48
Should be fixed by #2480

**Comment by mvorisek** [comment] 2022-10-03 11:16
Thanks to https://github.com/lubber-de/Fomantic-UI/pull/51 this problem will be fixed by #2480

**Comment by lubber-de** [comment] 2022-10-03 14:57
btw, i'll now take a look at the mentioned docs issues. But, please, in the future create separate issues for each problem you encounter, so we can keep track on each issue separately as the docs issue mentioned are independend of the font linegap issue

**Comment by lubber-de** [comment] 2022-10-04 20:25
The mentioned docs console errors are fixed by https://github.com/fomantic/Fomantic-UI-Docs/pull/381

**Closed** 2022-10-10 06:16 UTC
Labels: type/bug, browser/firefox
