### ISSUE TITLE
Popups activated by click don't work in 2.7.5

### ISSUE THREAD

**Issue by Merlin04** [fomantic/Fomantic-UI#766] opened 2019-05-23 17:34 UTC
# Bug Report

This bug appeared in 2.7.5. 

## Steps to reproduce
1. Create a pop-up activated by a click on an element. 
2. Try to click it
3. See that nothing happens

## Expected result
The pop-up opens

## Actual result
It doesn't

## Testcase

https://jsfiddle.net/1L5jrwmp/2/

## Version
2.7.5

**Comment by Merlin04** [comment] 2019-05-23 17:35
Forgot to add: it doesn't work in chrome or Firefox, but it does work on Edge 25

**Comment by lubber-de** [comment] 2019-05-23 19:38
Unfortunately i cannot reproduce this. 😢 
Your provided jsfiddle runs fine for me on chrome, firefox,edge and even ie11  as expected. The settings popup opens when i click on the button. I also tried chrome+firefox mobile (just add "/show" to the jsfiddle url)

**Comment by Merlin04** [comment] 2019-05-23 20:08
I updated my browser and it worked fine. I don't know the specific versions of the browsers that it doesn't work on, but it doesn't seem to work on Firefox 57.

**Comment by lubber-de** [comment] 2019-05-23 20:57
Works also fine on Firefox 57, tested on Browserstack
![ff57popup](https://user-images.githubusercontent.com/18379884/58286015-27619980-7dae-11e9-814d-78542243c449.gif)

**Comment by Merlin04** [comment] 2019-05-23 23:02
Maybe it's exclusive to windows? It definitely didn't work for me, so that might be the cause.

**Comment by hammy2899** [comment] 2019-05-24 06:39
@Merlin04 Have you tried disabling any extensions you might have.

**Comment by Merlin04** [comment] 2019-05-24 14:22
I am not using any extensions.

**Comment by lubber-de** [comment] 2019-05-24 20:39
I am sorry, but i still cannot reproduce on any current OS/Browser. I also tested using browserstack on Mac and Windows with Firefox 57 and it worked as expected. Chrome & Firefox on Ubuntu also worked for me.
As the behavior was fixed for you by upgrading your browsers and FUI supporting the last 2 versions of FF only i am closing this for now.

**Closed by lubber-de** 2019-05-24 20:39 UTC
Labels: :thinking: cannot reproduce

**Comment by Merlin04** [comment] 2019-06-03 17:08
The problem also occurs on Google Chrome 67.0.3396.87 (Official Build) (32-bit). I know it probably won't ever be fixed but I thought I'd leave this information here anyway.
