### ISSUE TITLE
Table Sortable conflict with Popup

### ISSUE THREAD

**Issue by lesliechw** [fomantic/Fomantic-UI#524] opened 2019-02-26 08:42 UTC
# Bug Report

## Steps to reproduce
1. Have a button with Popup initialized on a table column of each row.
2. Add sortable to table.
3. Sort once, Popup will not work anymore.

## Screenshot (when possible)
![]()

## Version
x.x.x

**Comment by ColinFrick** [comment] 2019-02-26 08:44
Could you provide a jsfiddle?

**Comment by lesliechw** [comment] 2019-02-26 08:57
Ok I'll update here once done. Busy with the code now. I removed the sorting function at the moment.

**Comment by lesliechw** [comment] 2019-02-26 09:01
@ColinFrick At the fiddle doesn't have Meteor JS. Is that ok?

**Comment by ColinFrick** [comment] 2019-02-26 09:06
@lesliechw Yes that's ok. You should be able to reproduce the problem with only fui / sortable right?

**Comment by lesliechw** [comment] 2019-02-26 09:28
@ColinFrick I'll try it later. Not too sure about that cause each row is a sub template of Meteor and each sub template initialize it's own Popup.

**Comment by hammy2899** [comment] 2019-05-09 17:32
@lesliechw Is this still an issue or can we close this now?

**Comment by lubber-de** [comment] 2019-07-15 18:09
Closing because of no response and missing Testcase. Happy to reopen if a reproducable jsfiddle is provided

**Closed by lubber-de** 2019-07-15 18:09 UTC
Labels: :memo: needs test case, 🔄 waiting for response
