### ISSUE TITLE
[Form validation] Regex gives Uncaught TypeError on validation

### ISSUE THREAD

**Issue by Merlin04** [fomantic/Fomantic-UI#1368] opened 2020-03-16 04:02 UTC
I have a simple form set up with one input and a submit button. I want to validate the field using a regex:
```js
$('document').ready(() => {
    $('.ui.form').form({
        fields: {
            data: [{type: "regExp[/.+=.+/g]", prompt: "Please enter a valid URL parameter string"}]
        }
    });
});
```
When I click the submit button, I get this error:
```
Uncaught TypeError: e.type.match is not a function
    at Object.bracketedRule (semantic.min.js:11)
    at Object.ancillaryValue (semantic.min.js:11)
    at Object.rule (semantic.min.js:11)
    at Object.<anonymous> (semantic.min.js:11)
    at Function.each (jquery.min.js:2)
    at Object.field (semantic.min.js:11)
    at Object.<anonymous> (semantic.min.js:11)
    at Function.each (jquery.min.js:2)
    at Object.isValid (semantic.min.js:11)
    at HTMLFormElement.form (semantic.min.js:11)
```

I've tested this using both Firefox and the Chromium built into Electron, and I'm using the latest version of Fomantic UI (2.8.4).  

Here's a link that shows the issue: https://jsfiddle.net/xn7pg3f1/2/

**Comment by exoego** [comment] 2020-03-16 04:33
Currently, form variation using regular expression is not implemented.
So, I rephrased the isssue title so it looks feature request, not a bug report.

You may implement it as custom rules.
https://fomantic-ui.com/behaviors/form.html#adding-custom-rules

PR welcome !

**Comment by exoego** [comment] 2020-03-16 04:45
@Merlin04 

Rules should be written in `rules` property of each `field` property`.
I made a working example.
https://jsfiddle.net/ts0dc7ny/

```
// wrong
fields: {
  data: [{type: "regExp[/.+=.+/g]", prompt: "Please enter a valid URL parameter string"}]
},

// correct
fields: {
  data: {
    rules: [{type: "regExp[/.+=.+/g]", prompt: "Please enter a valid URL parameter string"}]
  }
},
```

**Comment by lubber-de** [comment] 2020-04-17 16:54
Closing because of no more response assuming the explanation in the last post was clear and solves the issue.

**Closed by lubber-de** 2020-04-17 16:54 UTC
Labels: state/awaiting-response, type/usage
