### ISSUE TITLE
[menu] vertical menu left aligned icons

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2234] opened 2022-02-14 12:27 UTC
# Feature Request
Icons should optionally be allowed to be left aligned in vertical menus, rather than being forced to be right aligned

![image](https://user-images.githubusercontent.com/1376843/153864037-ecf47860-916c-4df3-b462-2b82d9506299.png)

**Comment by lubber-de** [comment] 2022-07-08 04:52
Duplicate of #493 
You might try overriding `@verticalIconFloat` as siuggested in https://github.com/fomantic/Fomantic-UI/issues/493#issuecomment-464061291

**Closed by lubber-de** 2022-07-08 04:52 UTC
Labels: type/feat, state/awaiting-triage

**Comment by ghabriel25** [comment] 2025-05-07 07:02
@jamessampford @lubber-de Sorry to bump old thread, just a workaround for this, wrap your text and icon with `span` should do the trick.
```blade
<div class="ui vertical menu>
    <div class="item">
        <span>
            <i class="home icon></i>
            Home
        </span>
    </div>
</div>
