### ISSUE TITLE
[Multiple Select Dropdown] Multi-line selected elements reappear after clear

### ISSUE THREAD

**Issue by themattyg** [fomantic/Fomantic-UI#1835] opened 2021-01-08 17:45 UTC
# Bug Report
On Safari iOS, when using a multiple select dropdown, if your selections wrap (add extra lines), when trying to clear a selection on the second (or beyond) lines, the selection disappears and gets replaced with a selection from the top of the list. It works as expected on all major desktop browsers, but iOS Safari displays incorrect behaviour.

## Steps to reproduce

1. Open a multi-select dropdown.
2. Select enough options to wrap to a second line.
3. Try to remove the item from the second line

## Expected result
When tapping the X on a selection, it gets removed and not replaced or re-added.

## Actual result
Assuming the list has any options left, the removed selection gets replaced with the option at the top of the list.

## Testcase
https://jsfiddle.net/themattyg/z96xa3ue/4/

## Screenshot
https://www.icloud.com/photos/#0X2LvrPsC30HAGZxDTJJgDqjQ

## Version
2.8.6

**Comment by lubber-de** [comment] 2021-01-08 21:29
I am sorry, but i cannot reproduce the behavior i have seen in your uploaded video by the given jsfiddle.
Please adjust the jsfiddle until its reproducable or a hint what i am doing wrong 😉 
![unselectnotreproducable](https://user-images.githubusercontent.com/18379884/104065989-f04d2f80-5200-11eb-87ba-0d1b7618f734.gif)

**Comment by lubber-de** [comment] 2021-01-08 21:39
Ok, i can reproduce if really trying on Safari iOS as you initially told. 
Sorry for that. 🙄 

It also happens on Android. Desktop Browsers are not affected. We'll investigate

Your jsfiddle can be tested on mobile using this link
https://fomantic-ui.com/jsfiddle/#!themattyg/z96xa3ue/4/

**Comment by lubber-de** [comment] 2023-02-26 17:49
This does not seem to be happening anymore in latest mobile browsers and latest FUI version. Closing.

**Closed by lubber-de** 2023-02-26 17:49 UTC
Labels: type/bug, lang/javascript, device/mobile, state/awaiting-investigation
