### ISSUE TITLE
[dropdown] onChange fired too many time on multiselect

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1633] opened 2020-08-06 15:59 UTC
# Bug Report
I'm using a dropdown in a modal and I'm experiencing issue about `onChange` event.
The dropdown has preselected items and then it triggers onChange.
Is it ok that in case of multiselect dropdown onChange event is triggered for every item selected?

## Steps to reproduce
1. Open modal and see in console how many times is triggered onChange: 2 times instead of one time (because there a 2 selected items)
2. Close modal and reopen it: now onChange is triggered 4 times
Why this behaviour?

## Expected result
Should the multiselect dropdown fire `onChange` event just ONE TIME even in case of more than preselected items?
Why closing and reopening modal make it doubling onChange events?

## Actual result
onChange event firing is double.
You can try adding more choices and set them in the dropdown. When you open the modal for the first time you will get onChange triggered for every item in the select and two onChange triggered for every item when you reopen the modal.

## Testcase
Here is my StackBlitz: https://stackblitz.com/edit/angular-ysshfb

## Version
2.8.6

**Comment by lubber-de** [comment] 2020-08-06 16:02
Duplicate of #165

**Closed by lubber-de** 2020-08-06 16:02 UTC
Labels: type/duplicate

**Comment by smartm0use** [comment] 2020-08-07 07:18
Intead what about calls doubling by reopening modal?

**Comment by lubber-de** [comment] 2020-08-07 08:56
Here is a jsfiddle for your described behavior https://jsfiddle.net/lubber/rhd8zvek/6/
This is current expected behavior
- The first console entry occurs upon creation of the dropdown (regardless if its inside modal or not)
- The second console entry occurs because of your `set selected` behavior

As you can see, the console entries do **not** repeat again when you close/open the modal, so i cannot reproduce this outside of your angular environment
