### ISSUE TITLE
Secondary Pointing Tabs: Active Item Loses Color on Hover

### ISSUE THREAD

**Issue by qJake** [fomantic/Fomantic-UI#1336] opened 2020-02-19 17:20 UTC
Pen to demonstrate bug: https://codepen.io/qJake/pen/JjdRYrX

When creating a `ui pointing secondary menu`, where each individual `item` has a color (e.g. `red item`, `purple item`, etc.), the active item loses its color on hover (possibly due to a CSS specificity bug).

![image](https://user-images.githubusercontent.com/652006/74857694-aff37300-5309-11ea-96c8-9de5ba460d99.png)

**Workaround:** You can color each thing in the `item` individually (e.g. `red abc icon` and `ui red text`), but this is somewhat "dirty" from an HTML standpoint.

**Comment by lubber-de** [comment] 2020-02-19 17:25
This is fixed by #1322

**Comment by lubber-de** [comment] 2020-02-19 17:25
duplicate of #1321

**Closed** 2020-02-25 11:09 UTC
Labels: lang/css, type/bug, type/duplicate
