### ISSUE TITLE
Fast continuous clicking of accordion titles breaks accordion

### ISSUE THREAD

**Issue by ben-eSM** [fomantic/Fomantic-UI#809] opened 2019-06-12 15:11 UTC
# Bug Report

## Steps to reproduce
1. Implement an accordion to your site
2. Continuously fast click on a title

## Expected result
The content should continue to open/close, no matter how often and fast one clicks a title.

## Actual result
After a few clicks there's an javascript error showing up and the accordion or at least the corresponding content won't open or close any longer.

## Version
2.7.5

**Comment by hammy2899** [comment] 2019-06-12 15:19
Confirmed, needs a check for whether the event exists before this line https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/transition.js#L218

Testcase: https://jsfiddle.net/3r16mg95/

**Comment by lubber-de** [comment] 2019-06-12 15:24
Duplicate of #747 
Fixed by #748 and part of FUI 2.7.6 🙂

**Closed** 2019-06-16 19:52 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :paperclip: duplicate, lang: JavaScript :scroll:
