### ISSUE TITLE
[Calendar] Popup stays open with form validation in a modal window

### ISSUE THREAD

**Issue by huzii7** [fomantic/Fomantic-UI#786] opened 2019-05-30 17:13 UTC
# Bug Report

## Steps to reproduce
1. Open Modal for the second time (first time works as expected)
2. Click on calendar input fields
3. Both calendar popups remain open

## Expected result
Calendar popup should close upon clicking another input field

## Actual result
Calendar popup remains open after clicking another input field

## Testcase
https://jsfiddle.net/knebv9ma/4/

## Screenshot (when possible)
<img width="665" alt="Screenshot 2019-05-30 at 18 09 04" src="https://user-images.githubusercontent.com/33911236/58650305-32647e80-8306-11e9-963c-da194bf9a935.png">

## Version
2.7.5

**Comment by lubber-de** [comment] 2019-05-30 21:38
Duplicate of #746 
Fixed by #767 
See your adjusted jsfiddle here https://jsfiddle.net/af48Lteq/

**Closed** 2019-06-16 19:52 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :paperclip: duplicate, lang: JavaScript :scroll:
