### ISSUE TITLE
Dropdown remote getting type error: e is null

### ISSUE THREAD

**Issue by cafeclimber** [fomantic/Fomantic-UI#505] opened 2019-02-20 22:05 UTC
# Help Wanted

## Problem
I am trying to get populate a dropdown with remote data using the api, but no matter what I try, the console always shows: `TypeError: e is null`

My backend is Django. I've tried returning what Django returns doing a '.all()' query and fixing the response in an onResponse call in my js, but this didn't work. I've also tried creating the correct format in Django and returning JSON of the correct form (according to [this](https://fomantic-ui.com/modules/dropdown.html#match-search-query-on-server)) but I get the same error. An example of the response from my server is:

```javascript
{
  "success": true,
  "results": [
    {
      "name": "Adafruit",
      "value": 1
    },
    {
      "name": "SparkFun",
      "value": 2
    }
  ]
}
```

And here is the relevant javascript:

```javascript
    $('#manufacturer').dropdown({
        apiSettings: {
            debug: true,
            cache: false,
            action: 'get manufacturer list',
        },
    });
```

The debug output shows all the steps are completing succesfully:

```
... Changing setting ...
... Looking up url for action ...
... Querying URL ...
... Throttling request ...
... Sending throttled request ...
... Checking JSON returned success ...
... Response passed success test ...
... Successful API Response ...
```

With the final step showing my response in the correct form.

The exact error message is:
```
TypeError: e is null[Learn More] semantic.min.js:11:86696
```

**Comment by lubber-de** [comment] 2019-02-20 22:29
`e`  in the minified version at the described source seems to be the `response` in the `request.done()` function, so i guess the response is somehow broken. Maybe something additional is sent by your backend in the stream (non-printable characters? wrong content-type? )T he network tab of the chrome developer tools would probably tell you.

As the response is fetched by jquery functionality: Which jquery version are you using? Try the latest 3.3.1

You  may also try to use the non-minified version `semantic.js` to get a more clear idea where the error 
 and what exactly occurs. 

Anyway: Would be really nice and much easier to help if you can create  a reproducable jsfiddle for better investigation. Thanks

**Comment by cafeclimber** [comment] 2019-02-21 00:12
Sorry about not including a jsFiddle. I don't know that I could reproduce the error easily. Not using the minified js yields:

```
TypeError: preSelected is null[Learn More] semantic.js:6737:21
```
That line shows
```
var preSelected = $input.val();
```
where `preSelected` becomes `null`

**Comment by lubber-de** [comment] 2019-02-21 07:03
Please provide your html code for the `#manufacturer ` element (incl. child's, so the whole dropdown element) that's why it's always easier to help. 
Although we could fix the code there, I believe your html code misses the input element, which would lead into the described  situation. `val()` returns null only if `$input` is undefined, which should not be the case if dropdown is setup properly

**Comment by lubber-de** [comment] 2019-02-21 07:42
OK, after some guessing i found out this seems to happen, when you have an empty `select` tag used as the dropdown element. I'll provide a fix

**Comment by lubber-de** [comment] 2019-02-21 08:33
@cafeclimber Should be fixed by #506

**Comment by cafeclimber** [comment] 2019-02-21 20:17
Again, sorry for not including enough information. My HTML is very simple. I tried to take it from the example [here](https://fomantic-ui.com/modules/dropdown.html#search-selection). It's wrapped in a modal.

```html
<div class="ui modal">
    <i class="close icon"></i>
    <div id="modal-header" class="header">
    </div>
    <div class="content">
        <h4 class="ui horizontal divider header"><i class="industry icon"></i>Manufacturer</h4>
        <select class="ui search dropdown" id="manufacturer"></select>
    </div>
    </div>
</div>
```

**Comment by lubber-de** [comment] 2019-02-21 20:21
@cafeclimber Then my guess with the empty `select` was correct 😄

**Comment by lubber-de** [comment] 2019-02-21 20:23
See your code is working again here: https://jsfiddle.net/dj271oLr/

**Comment by cafeclimber** [comment] 2019-02-21 20:24
It was! Lol thanks for the help and the PR.

**Closed** 2019-04-02 08:10 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, lang: JavaScript :scroll:
