### ISSUE TITLE
Floating dropdown’s menu can be escaped by keyboard without it closing

### ISSUE THREAD

**Issue by chris-morgan** [fomantic/Fomantic-UI#2101] opened 2021-09-13 01:52 UTC
https://fomantic-ui.com/, the Dropdown section, open the filter one (the second one), press Tab twice, and you’re out of the popup and onto the next field, but the popup is still open until you click outside it, or perform some keyboard action that *does* close it (e.g. return to it and select an item with Enter).

**Comment by lubber-de** [comment] 2021-09-13 13:44
I am not sure which example you are talking about. The [Floating dropdown example](https://fomantic-ui.com/modules/dropdown.html#floating) does not have a filter and the second example there is a simple css only dropdown which works on hover, so of course does not close the menu when pressing tab (but the mouse pointer stays where it is.

There is a "[second filter example](https://fomantic-ui.com/modules/dropdown.html#divider)" at the content section, but i cannot reproduce your described behavior there. Pressing Tab twice works fine and closes the menu popup
![whichfilter](https://user-images.githubusercontent.com/18379884/133094697-0b73273b-6d98-4dc4-914c-36fb6fdfa355.gif)


So, please 🙂 : Which exact example are you referring to? (Or create a jsfiddle)

**Comment by lubber-de** [comment] 2022-10-02 16:24
Closing because of no more response

**Comment by chris-morgan** [comment] 2022-10-02 16:46
Exactly what I *said*. https://fomantic-ui.com/, the Dropdown section. Not some other page.

**Comment by jamessampford** [comment] 2022-10-02 17:44
@lubber-de it may be the 2nd one in https://fomantic-ui.com/modules/dropdown.html#scrolling tabbing through every single dropdown there until getting something as described. Doesn't seem to happen when tabbing backwards

I've also noticed when tabbing through, whilst most dropdowns with an `input` inside for search after the dropdown opens the next tab will focus on the input however, not all of them do (eg. will close the dropdown instead of focusing or may very briefly focus, but then close)

**Comment by lubber-de** [comment] 2022-10-02 19:58
Fixed by #2475

**Closed** 2022-10-10 06:15 UTC
Labels: type/bug
