### ISSUE TITLE
[Help] There are some way to create a segment with fixed height with a vertical roll bar?

### ISSUE THREAD

**Issue by guilhermej** [fomantic/Fomantic-UI#1383] opened 2020-03-29 19:08 UTC
# Help Wanted
I want to create a fixed heigth segment with a vertical bar to roll.

I tried to set max-height to the segment and add a overflow-y-auto class but it not worked.

I'm using Fomantic 2.7.X

**Comment by lubber-de** [comment] 2020-03-29 19:54
Well, it works fine for me the exact way, you described. See https://jsfiddle.net/jo79ta3z/

**Comment by lubber-de** [comment] 2020-04-17 13:26
Closing because of no more response and unability to reproduce.
Happy to reopen if you could provide a reproducable jsfiddle.

**Closed by lubber-de** 2020-04-17 13:26 UTC
Labels: state/cannot-reproduce, type/usage
