### ISSUE TITLE
vertical menu didn't work as expected

### ISSUE THREAD

**Issue by labby** [fomantic/Fomantic-UI#1514] opened 2020-06-08 14:49 UTC
# Bug Report
vertical menu didn't work as expected in 2.8.5, mouse events obviously don't work.
I switched back to 2.8.4 and the menu works again.

![menu_284](https://user-images.githubusercontent.com/1763282/84044503-f566a980-a9a7-11ea-9b37-7f3f504a38c8.jpg)

**Comment by lubber-de** [comment] 2020-06-08 14:58
That's probabyl already fixed by #1376 
Could you please share your relevant code as jsfiddle, so we can reproduce and try to see if the mentioned PR really fixes it?

**Comment by labby** [comment] 2020-06-08 15:06
> That's probably already fixed by #1376
? this is from March and 2.8.5 was released on 1st of June.

Sorry but only less time this week, this was just to inform you that it doesn't work as expected in 2.8.5 but in 2.8.4 and all releases before

**Comment by lubber-de** [comment] 2020-06-08 15:50
Sorry, that was of course the wrong Pr reference 🙄 
I corrected my post and was referencing to #1505 

Please provide some example code here, if you cannot create a jsfiddle

If you also cannot provide code, then i am sorry , but we cannot fix/analyze your issue, because we cannot guess code out of screenshots :wink:

**Comment by labby** [comment] 2020-06-08 16:25
> I corrected my post and was referencing to #1505

Seems that the bug is solved

This is part of the code that was built in the above image (used twig template engine)
As it is hard to post that code here I attached a text-file with the code
[code.txt](https://github.com/fomantic/Fomantic-UI/files/4747236/code.txt)

**Comment by lubber-de** [comment] 2020-06-08 16:52
Thanks, i could reproduce now . Infact it's fixed by #1505 as i already guessed 😃 
The mouse events are still working, but the dropdown was hidden... 🙄 

Here are some jsfiddles
### v2.8.5 - Broken as you described
https://jsfiddle.net/lubber/7m1wphdv/8/

### v2.8.5 - Working again with fix from #1505 
https://jsfiddle.net/lubber/7m1wphdv/7/

**Comment by ko2in** [comment] 2020-06-08 17:48
@lubber-de , I think what he's talking about is this kind of vertical menu (https://jsfiddle.net/8a0srfxd/1/). @labby , please lets me know if it's what you're asking for.

But, I couldn't reproduce your issue with the current version (2.8.5). It's working fine.

But, I could reproduce this (https://jsfiddle.net/hg75w1qp/) with the latest fix #1505. :smile: 

It's because of `right` flag in `ui right simple dropdown item`. Without the `right` flag, it works fine (https://jsfiddle.net/o2w6bfvm/).

I'm not sure do we really need the `right` flag here. If so, I'll have to refactor and send another PR to solve this.

**Comment by labby** [comment] 2020-06-09 07:18
Thanks for help.
I am afraid both of you are right.
With my code.txt neither mouse_hover nor mouse_click is working to expand the menu.
@lubber-de : your fiddle is working with mouse_click but not with mouse_hover
@ko2in : this is the expected behaviour: https://jsfiddle.net/o2w6bfvm/ but I don't know why you cannot reproduce the bug with 2.8.5 :-(

**Comment by lubber-de** [comment] 2020-06-09 08:12
@labby My example also works on `hover` :)
See https://jsfiddle.net/sm2vcayu/

**Comment by labby** [comment] 2020-06-09 08:39
ok :-)  sorry for that
I could swear this was not workin with mouse_hover :-)

**Closed** 2020-06-17 17:00 UTC
Labels: lang/css, priority/high, type/bug
