### ISSUE TITLE
[toast]Toast with Actions - approve, deny 

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#566] opened 2019-03-12 16:53 UTC
# Feature Request
on Actions - Approve and deny and right image(Whatever it is)
## Description
feature same OSX Notification Center with active Approve and deny

## Example
![image](https://user-images.githubusercontent.com/33564576/54219315-403a0d00-452a-11e9-8359-15afabbdb1af.png)

**Comment by lubber-de** [comment] 2019-03-12 17:03
Duplicate of #160

**Comment by lubber-de** [comment] 2019-10-28 22:28
Possible by #1129

**Closed** 2019-11-14 08:38 UTC
Labels: :heavy_check_mark: next release, :paperclip: duplicate
