### ISSUE TITLE
enabledDates is enable next month date tan array value

### ISSUE THREAD

**Issue by HarshBharga** [fomantic/Fomantic-UI#1390] opened 2020-04-01 13:53 UTC
# Bug Report
enabledDates is enable next month date tan array value

## Steps to reproduce
1.
2.
3.

## Screenshot (when possible)
![]()

## Version
x.x.x

**Comment by lubber-de** [comment] 2020-04-01 14:14
Sorry, I don't get your point 🙁Please fill out the bug template and provide a jsfiddle or at least a code snippet to reproduce. Thanks

**Comment by lubber-de** [comment] 2020-04-05 21:42
Please see the working docs examples https://fomantic-ui.com/modules/calendar.html#enable-only-specific-dates . I cannot see that the whole months gets enabled as you probably meant by the issue header.
If you still have trouble using `enabledDates` functionality, please provide a reproducable jsfiddle and a complete description what's not working and what's  the expected result. Thanks. Closing because of this. Happy to repopen if you provide the necessary informations. 😉

**Closed by lubber-de** 2020-04-05 21:42 UTC
Labels: needs-more-info
