### ISSUE TITLE
[Card] Dimmer stays visible

### ISSUE THREAD

**Issue by Thanty** [fomantic/Fomantic-UI#795] opened 2019-06-04 12:30 UTC
# Bug Report

Dimmer inside card stays visible if you leave mouse too fast (before animation ends).

Semantic UI doesn't have this type of problem (see docs): https://semantic-ui.com/views/card.html#image

## Testcase
https://jsfiddle.net/tncqskro/

## Expected result

![expected](https://media.giphy.com/media/J1peFvxFBPD9ieCDOb/giphy.gif)

## Actual result

![screenshot](https://media.giphy.com/media/fubd8PZQRqXLMzS3A0/giphy.gif)

## Version
2.7.5

**Comment by lubber-de** [comment] 2019-06-04 15:14
Duplicate of #747
Fixed by #748
As a workaround try adding https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@930f48447ab8998729e919697112517297b04fef/src/definitions/modules/transition.js after fui 2.7.5
See your adjusted jsfiddle here: https://jsfiddle.net/nyzjkbrd/

**Closed** 2019-06-16 19:52 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :paperclip: duplicate, lang: JavaScript :scroll:
