### ISSUE TITLE
[Dropdown] Multiple Selection onChange acts like onAdd when data is initialized with JavaScript

### ISSUE THREAD

**Issue by davidlav** [fomantic/Fomantic-UI#1105] opened 2019-10-18 03:36 UTC
# Bug Report

Multiple Selection Dropdown onChange listener behaves almost identically to onAdd when data is initialized via JavaScript as opposed to through HTML.

## Test Case

Add Male, add Female, remove Male, remove Female.

## Expected result

With HTML:

```
<select class="ui fluid search multiple dropdown" id="dropdown" multiple>
  <option value="male">Male</option>
  <option value="female">Female</options>
</select>
```

and JavaScript:

```
$('#dropdown')
      .dropdown({
        onChange: value => console.log('change', value),
        onAdd: value => console.log('add', value),
        onRemove: value => console.log('remove', value),
      })
```

Console output:
```
"add" "male"
"change" ["male"]
"add" "female"
"change" ["male", "female"]
"remove" "male"
"change" ["female"]
"remove" "female"
"change" []
```

_This is how it should be._  onChange shows current selection after every addition and removal.

## Actual result

With HTML:

```
<select class="ui fluid search multiple dropdown" id="dropdown" multiple>
</select>
```

and JavaScript:

```
$('#dropdown')
      .dropdown({
        onChange: value => console.log('change', value),
        onAdd: value => console.log('add', value),
        onRemove: value => console.log('remove', value),
        values: [
          {
            name: 'Male',
            value: 'male'
          },
          {
            name     : 'Female',
            value    : 'female',
          }
        ]
      })
```

Console output:
```
"add" "male"
"change" ["male"]
"add" "female"
"change" ["female"]
"remove" "male"
"remove" "female"
```

_onChange only firing on additions, and even then only shows the added element, not all **added/selected** elements._

## Version
2.7.8

**Comment by lubber-de** [comment] 2020-08-06 16:01
Duplicate of #165

**Closed by lubber-de** 2020-08-06 16:01 UTC
Labels: lang/javascript, state/awaiting-investigation
