### ISSUE TITLE
File input not triggering within tabs

### ISSUE THREAD

**Issue by ricohumme** [fomantic/Fomantic-UI#1036] opened 2019-09-25 10:29 UTC
This bug was already reported in SUI and confirmed but not resolved yet in FUI as of today.

Details: https://github.com/Semantic-Org/Semantic-UI/issues/6340

Could this be addressed in FUI ?

**Comment by hammy2899** [comment] 2019-09-25 10:36
I can't seem to reproduce this in FUI, what version are you using?

https://jsfiddle.net/ubn40d95/

**Comment by ricohumme** [comment] 2019-09-25 11:12
Just took a look, 2.7.5

**Comment by hammy2899** [comment] 2019-09-25 11:37
Just tried using 2.7.5 and it works fine, could you make a JSFiddle of your implementation so I can compare it to my test case.

**Comment by MartiVB** [comment] 2019-09-25 12:19
I create a new fiddle with the error : https://jsfiddle.net/Lxjscrk4/
So the error appear when you use the tab('change tab').

**Comment by jamessampford** [comment] 2019-09-25 12:24
Slightly amended JSFiddle correcting the JS so it works:
https://jsfiddle.net/v2soa96t/2/

**Comment by hammy2899** [comment] 2019-09-25 12:25
Thanks @MartiVB that seems to replicate it 👍

**Comment by hammy2899** [comment] 2019-09-25 12:26
@jamessampford your fiddle seems to work for me, what browser are yo using?

**Comment by jamessampford** [comment] 2019-09-25 12:29
Chrome 77 - basically I _think_ it is to do with the way the tab was set to change focusing on the data attribute that exists as the tab and segment

Using the JSFiddle from https://github.com/fomantic/Fomantic-UI/issues/1036#issuecomment-534994699

Removing the below
`$('[data-tab="one"]').tab('change tab', 'one');`
Leaving 
`$('.tabular.menu .item').tab();`

Both tabs and file input works as per normal

**Comment by MartiVB** [comment] 2019-09-25 12:35
@jamessampford that works for me!

**Comment by lubber-de** [comment] 2020-11-14 23:26
Closing, because reason for this was the selector for the `.tab` initialization, which should point to the menu items instead of the data attribute (which had selected both: menu item and segment as @jamessampford already pointed out)

**Closed by lubber-de** 2020-11-14 23:26 UTC
Labels: lang/javascript, type/bug
