### ISSUE TITLE
[scope] .val() returning null of dropdown multiple select

### ISSUE THREAD

**Issue by freedmandil** [fomantic/Fomantic-UI#2156] opened 2021-11-11 15:37 UTC
# Bug Report

After dynamically creating a multiple select dropdown and assigning the class: "ui fluid search multiple selection dropdown"
and then applying                         $('.dropdown').dropdown({fullTextSearch: 'exact'}} to the dropdown in the modal:
In a modal in the onShow: function.
everything works until that point
however, when submitting (onApprove), the #select_id).val() returns a null value even though multiple items were selected.

## Steps to reproduce

After dynamically creating a multiple select dropdown and assigning the class: "ui fluid search multiple selection dropdown"
and then applying                         $('.dropdown').dropdown({fullTextSearch: 'exact'}} to the dropdown in the modal:
In a modal in the onShow: function.
everything works until that point
however, when submitting (onApprove), the #select_id).val() returns a null value even though multiple items were selected.
## Expected result

the value(s) of the selected options in an array

## Actual result

null
## Version

2.8.7

**Comment by lubber-de** [comment] 2021-11-11 15:47
Please provide a reproducable jsfiddle for easier investigation. Thanks.

My first guess is, the dropdown is initialized before the modal is and the modal has `detachable: true` which would replace the dropdown inside the modal to a different dom node position which then looses its events...But this is ony a guess and depends on your real code.

**Comment by lubber-de** [comment] 2021-11-21 18:14
Here is a jsfiddle which implements your described situation:
https://jsfiddle.net/lubber/s4qxzh7p/12/

- Open console
- Select any value(s) in the dropdown
- click "approve"
-  See selected values at the console

Everything works as expected, so i cannot reproduce the mentioned null value issue.
I am closing this as it is not reproducable. Will reopen when you can provide a proper example. Feel free to adjust my jsfiddle for that purpose ;)

**Closed by lubber-de** 2021-11-21 18:14 UTC
Labels: needs-more-info
