### ISSUE TITLE
UI selectors matching when component not installed

### ISSUE THREAD

**Issue by TivoSoho** [fomantic/Fomantic-UI#916] opened 2019-08-05 09:52 UTC
I am not sure if this is exactly a bug, but would like to document this none the less. Especially as this only came up after the latest 2 releases.

## Steps to reproduce
1. Install fomantic ui without calendar
2. Use class "ui calendar" class for your custom calendar
3. Submit a form

## Expected result
Form is submitted without JS errors

## Actual result
JS errors will be present

## Error message
$calendar.calendar is not a function (coming from form validation)

## Version
2.7.7

# Why could it be considered a bug?
As mentioned, only came a problem now. 
Semantic UI does not include a calendar, so we use were free to use what we wanted and use the same namespace as that is what we started out with. As Fomantic UI calendar is included so on switch we just removed that component. However now it broke since it has a check for if it can find elements with the calendar selector. If it included without the component then it can find matching elements and cause problems - like we had. Our solution is to override the selector, but could be good if the component wasn't included that it wouldn't include the selector either (use something that wouldn't match anything). Could be useful to others as well if you switch from SUI to FUI and have your own calendar.

**Comment by lubber-de** [comment] 2019-08-05 11:33
Could you please provide a jsfiddle to reproduce? Because the mentioed call to `.calendar` should only happen when the validator finds at least one formfield with class `.ui.calendar`.
So it seems, although you use FUI without calendar, you probably still have a form field which is/was supposed to be a calendar field having the `ui calendar` class set. Then the form validator assumes the calendar module is present.

**Comment by lubber-de** [comment] 2019-08-05 11:34
uhm...just saw you already wrote you have that... 🙄 ,then we might just check for exising calendar module...i'll tag this as enhancement

**Comment by lubber-de** [comment] 2019-08-05 12:00
@TivoSoho 
Should be fixed by #918 
Please try to override the form functionality by temporary include 
https://cdn.jsdelivr.net/gh/fomantic/fomantic-ui@89a3aa95c24e74afd891754d069f1de0e052adce/src/definitions/behaviors/form.js

after your compiled semantic.js (or as a replacement for the existing form.js)

**Closed** 2019-09-02 08:35 UTC
Labels: :heavy_check_mark: next release, :zap: enhancement, lang: JavaScript :scroll:
