### ISSUE TITLE
[Form Validation] onDirty event unpredictable behavior

### ISSUE THREAD

**Issue by mightyvoodoo** [fomantic/Fomantic-UI#930] opened 2019-08-11 15:01 UTC
When we have a multiple select field inside form (with dropdown module or not) onDirty event behavior would be unpredictable.

https://jsfiddle.net/vtbyr8o1
Try to focus textarea first, then re-run and try to select/unselect options.

Thanks!

**Comment by prudho** [comment] 2019-09-03 09:57
This is something i can see in the JSFiddle, but cannot reproduce on my computer...

Do you have another sample of code that will trigger this behavior ?

**Comment by hammy2899** [comment] 2019-10-31 15:45
@mightyvoodoo Is this still an issue?

**Comment by mightyvoodoo** [comment] 2019-10-31 16:12
Hello there! Sorry for very long answer.
Currently I'm on the same version. As soon as possible I'll be able to update and check.
Thanks for replies :+1:

**Comment by lubber-de** [comment] 2020-03-27 17:01
@mightyvoodoo Do you still have an issue?

**Comment by mightyvoodoo** [comment] 2020-03-27 19:24
@lubber-de Hello, issue is still here, reproduced with latest Fomantic version. Only occurs on forms with multiple select instantiated via `<select multiple>`. With multiple select instantiated via `<div>` form has proper behavior.

**Comment by lubber-de** [comment] 2020-07-28 23:12
Fixed by #1612 
See your fixed jsfiddle here https://jsfiddle.net/lubber/sjnv3wkp/

**Comment by mightyvoodoo** [comment] 2020-07-29 06:12
@lubber-de Yep, fixed. Thanks!

**Closed** 2020-09-07 06:18 UTC
Labels: lang/javascript, type/bug
