### ISSUE TITLE
second.modal('hide') after first.modal('show') doesn't wok

### ISSUE THREAD

**Issue by makseq** [fomantic/Fomantic-UI#774] opened 2019-05-25 15:46 UTC
# Bug Report

## Steps to reproduce
1. I try to hide the first and show the second modal dialog: 
```
<script> 
           $('#first-dialog').modal('hide');
           $('#second-dialog').modal('show');
</script>
```

## Expected result

Normally opened second dialog after first hides. 
It worked in last version of Semantic! 

## Actual result

No dialog. Error in console: 

```
Uncaught TypeError: Cannot read property 'target' of undefined
    at Object.complete (VM1834 semantic.min.js:11)
    at Object.animate (VM1834 semantic.min.js:11)
    at Object.initialize (VM1834 semantic.min.js:11)
    at HTMLDivElement.<anonymous> (VM1834 semantic.min.js:11)
    at Function.each (jquery.min.js:2)
    at k.fn.init.each (jquery.min.js:2)
    at k.fn.init.C.fn.transition (VM1834 semantic.min.js:11)
    at Object.show (VM1834 semantic.min.js:11)
    at HTMLBodyElement.show (VM1834 semantic.min.js:11)
    at Object.invoke (VM1834 semantic.min.js:11)
```

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/501780/58371792-416dba00-7f1d-11e9-8700-a3beeacb967d.png)

## Version
Last one: Fomantic UI - 2.7.5

**Comment by lubber-de** [comment] 2019-05-26 07:22
Duplicate of #747
Fixed by #748 
As a workaround try adding https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@930f48447ab8998729e919697112517297b04fef/src/definitions/modules/transition.js after fui 2.7.5

In case this does not fix your issue, please provide a reproducable jsfiddle

**Closed** 2019-05-26 11:07 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, :paperclip: duplicate, lang: JavaScript :scroll:
