### ISSUE TITLE
[dimmer]dimmer hide not object after event

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#747] opened 2019-05-16 20:06 UTC
# Bug Report

## Steps to reproduce
1.dimmer show event
2.other event example input value
3.dimmer hide event
4.dimmer error not object(TypeError: undefined is not an object (evaluating 'event.target'))
5.dimmer not hide
6.before FUI 2.7.5 is fine

## Testcase
https://jsfiddle.net/allwe/kucxvf79/4/

## Screenshot (when possible)
![]()

## Version
2.7.5

**Comment by lubber-de** [comment] 2019-05-17 06:24
Regression since 353f90f0cb512edbe51397e454714bbd5719195c through #698 
Fixed by #748
See https://jsfiddle.net/Luzdq681/

**Comment by apple-idn** [comment] 2019-05-18 15:57
some time else error

> 
<img width="1139" alt="Jepretan Layar 2019-05-18 pukul 8 02 32 PM" src="https://user-images.githubusercontent.com/33564576/57972096-b5add800-79c8-11e9-82fb-ca533e2dd6a3.png">

**Comment by lubber-de** [comment] 2019-05-18 16:14
@apple-idn that's the same error. You are just using the minified version.

**Closed** 2019-06-16 19:52 UTC
Labels: :bug: confirmed bug, :heavy_check_mark: next release, lang: JavaScript :scroll:
