### ISSUE TITLE
Sliders don't work on Chromium Edge

### ISSUE THREAD

**Issue by bobjase** [fomantic/Fomantic-UI#1741] opened 2020-11-02 22:49 UTC
# Bug Report

Slider's dont work at all

## Steps to reproduce
1. Open Chromium Edge
2. Try to use sliders

## Expected result
Working sliders

## Actual result
Static sliders

## Screenshot (when possible)
![]()

## Version
v2.8

**Comment by lubber-de** [comment] 2020-11-03 08:10
I cannot reproduce this on current Edge using the Docs Page for slider https://fomantic-ui.com/modules/slider.html

Please share a jsfiddle with your code where it doesn't work for you, so we can investigate

![edgeslider](https://user-images.githubusercontent.com/18379884/97961812-40001c80-1db4-11eb-919a-ff5230a3683a.gif)

**Comment by bobjase** [comment] 2020-11-03 14:17
It's super weird for me.

Here is the jsfiddle I created: https://jsfiddle.net/bobjase/eypc4uqr/12/

and here is a video of it working intermittently: 


![ezgif com-gif-maker](https://user-images.githubusercontent.com/25090541/97996178-74280d00-1db5-11eb-938d-6a1b08e86422.gif)

**Comment by lubber-de** [comment] 2020-11-03 14:25
I unfortunately still cannot reproduce this by the given jsfiddle (using also latest Chromium Edge) 😢 

Try to disable the jsfiddle internal console and use the native console instead. (although it didn't effect me either)
Do you have other Browser plugins running ? It seems something is blocking Javascript in certain cases ?

**Comment by bobjase** [comment] 2020-11-03 14:37
lubber - thanks for getting back to me so promptly.

Before I reported the issue I tried looking in the native console - nothing of interest.

I also tried running it in incognito mode (to disable all extensions) - same result.

The strange thing is that it works reliably in Chrome. At this point I'm out of ideas and I'm gonna look for another slider.

Thanks anyway

**Comment by lubber-de** [comment] 2020-11-03 15:08
I really believe this is some Edge/jsfiddle issue... When you switch to native console: Does the console show some JS error?
can you click on the thumb of the slider when using DOM inspector?

These are only reasons i can imagine (all of them do not explain why it works in natrive chrome for you then): 
- something blocks JS execution
- some unexptecting JS error stops the event handler
- some extra invisible HTML element is covering the thumb 
- loading of the CDN links of the jsfiddle resources are blocked (either jquery  or semantic.js)

Could you also try to run it in presentation mode. For example
https://fomantic-ui.com/jsfiddle/#!bobjase/eypc4uqr/12/

I really would like to find out the reason

**Comment by lubber-de** [comment] 2020-11-03 15:12
BTW: Does it work for you at the [Docs page for slider](https://fomantic-ui.com/modules/slider.html)?

**Comment by bobjase** [comment] 2020-11-03 16:12
> BTW: Does it work for you at the [Docs page for slider](https://fomantic-ui.com/modules/slider.html)?

Does not work there

**Comment by lubber-de** [comment] 2020-11-03 16:25
Very weird... In your video gif it was at least working the first time... Do other js modules work in edge for you? Like modal or dropdown?

**Comment by lubber-de** [comment] 2020-11-03 16:36
Do you happen to have any extensions installed ? As the engine is the same in chrome and chromium edge (and chrome is working for you), and it also happens for  you on the docs page, i strongly believe it's either an extension in chromium edge or some setting there (i am still trying to reproduce this by changing lots of settings myself...without success, it always works as expected...but i don't have any extensions installed)

**Comment by bobjase** [comment] 2020-11-03 17:15
> Very weird... In your video gif it was at least working the first time... Do other js modules work in edge for you? Like modal or dropdown?

Every other module works for me - including modal and dropdown

**Comment by ko2in** [comment] 2020-11-03 19:24
Works also on my Edge Version 88.0.680.1 (Official build) dev (64-bit) on Ubuntu 20.04 LTS. All sliders on doc page works too.

Can you try to reinstall your Edge and see it keeps happening?

**Comment by lubber-de** [comment] 2020-11-11 09:27
Closing, because it has to be client specific and no more response .
I also checked using browserstack and still cannot reproduce.

**Closed by lubber-de** 2020-11-11 09:27 UTC
Labels: browser/edge, needs-more-info, state/cannot-reproduce
