### ISSUE TITLE
[Tab] Tab history using historyType=hash does not restore last active tab in 2.9.x

### ISSUE THREAD

**Issue by MLukman** [fomantic/Fomantic-UI#2769] opened 2023-04-26 15:38 UTC
# Bug Report
Using 2.9.x, tab history using historyType=hash no longer restores the last selected tab upon reload/navigation. This bug even affects the official documentation @ https://fomantic-ui.com/modules/tab.html#/examples (notice that navigating to that link does not activate the "Examples" tab)

## Steps to reproduce
1.  Just follow the documentation on tab history @ https://fomantic-ui.com/modules/tab.html#with-hash-tags to create a simple tabset with minimum two tabs
2. Click on other than the first tab. Ensure the history feature is enabled by observing that the URL hash changes.
3. Reload the URL that includes the tab hash.

## Expected result
The last active tab was restored.

## Actual result
The first tab was activated, ignoring the tab hash.

## Testcase
This is the jsfiddle @ https://jsfiddle.net/ky9was7m/1/ but since jsfiddle uses iframe we can't see nor reload the URL hash.

## Version
2.9.x (since 2.9.0)
This issue does not affect 2.8.x

**Comment by lubber-de** [comment] 2023-04-26 22:11
This seems to be a docs issue, as i was not able to reproduce this using your jsfiddle code locally and FUI 2.9.x
However, i _was_ able to reproduce when using the outdated jquery.address plugin, which is used on the docs pages, instead of the latest from your jsfiddle.

After i updated the history plugin to the latest version, the issue was gone locally as well.
For me it did not make any difference between FUI 2.8.x and 2.9.x, the only difference was the jquery.address fix

I fixed this in https://github.com/fomantic/Fomantic-UI-Docs/pull/464

**Comment by MLukman** [comment] 2023-05-10 11:14
Hi @lubber-de , here is a simple HTML that demonstrates the issue. All the scripts are pulled from CDN.

Note that by changing line 8 to use fomantic 2.8, the issue disappears.

    <!DOCTYPE html>
    <html>
        <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9/dist/semantic.min.css">
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/jquery-address@1.6/src/jquery.address.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9/dist/semantic.min.js"></script>
            <script>
            $(function() {
                $('.item[data-tab]')
                  .tab({
                    history : true,
                    historyType: 'hash'
                  })
                ;
            });
            </script>
        </head>
        <body>
            <div class="ui pointing secondary menu">
                <a class="item" data-tab="first">First</a>
                <a class="item" data-tab="second">Second</a>
                <a class="item" data-tab="third">Third</a>
            </div>
            <div class="ui tab segment" data-tab="first">
                <div class="ui top attached tabular menu">
                    <a class="item" data-tab="first/a">1A</a>
                    <a class="item" data-tab="first/b">1B</a>
                    <a class="item" data-tab="first/c">1C</a>
                </div>
                <div class="ui bottom attached tab segment" data-tab="first/a">1A
                </div>
                <div class="ui bottom attached tab segment active" data-tab="first/b">1B
                </div>
                <div class="ui bottom attached tab segment" data-tab="first/c">1C
                </div>
            </div>
            <div class="ui tab segment" data-tab="second">
                <div class="ui top attached tabular menu">
                    <a class="item" data-tab="second/a">2A</a>
                    <a class="item" data-tab="second/b">2B</a>
                    <a class="item" data-tab="second/c">2C</a>
                </div>
                <div class="ui bottom attached tab segment" data-tab="second/a">2A
                </div>
                <div class="ui bottom attached tab segment" data-tab="second/b">2B
                </div>
                <div class="ui bottom attached tab segment" data-tab="second/c">2C
                </div>
            </div>
            <div class="ui tab segment" data-tab="third">
                <div class="ui top attached tabular menu">
                    <a class="item" data-tab="third/a">3A</a>
                    <a class="item" data-tab="third/b">3B</a>
                    <a class="item" data-tab="third/c">3C</a>
                </div>
                <div class="ui bottom attached tab segment" data-tab="third/a">3A
                </div>
                <div class="ui bottom attached tab segment" data-tab="third/b">3B
                </div>
                <div class="ui bottom attached tab segment" data-tab="third/c">3C
                </div>
            </div>
        </body>
    </html>

**Comment by lubber-de** [comment] 2023-05-12 22:15
@MLukman Thanks, i was now able to reproduce!
Fixed by #2786

**Closed** 2023-09-08 05:05 UTC
Labels: type/bug, type/docs
