### ISSUE TITLE
Toast is causing major memory leak

### ISSUE THREAD

**Issue by luki009** [fomantic/Fomantic-UI#2704] opened 2023-02-18 11:23 UTC
# Bug Report
jQuery.toast  is causing memory leak. Looks like toast will creating timers in infinite loop and therefore it will never be garbage collected.
4 - 6 toast messages will eat 4gb of memory heap in less then 30 mins.

## Steps to reproduce
1. Create 1 to 4  $.toast() and observer Memory tab in developer tools 

## Expected result
Toast message is garbage collected after it expires.

## Actual result
JS memory heap will start increasing after toast message display and will not stop until page refresh. which will eventually cause browser to crash with err: Out of Memory

## Version
Fomantic 2.9.1
jQuery 3.1.1

**Comment by lubber-de** [comment] 2023-02-19 14:29
I am not able to reproduce this behavior.

Please check the following jsfiddle.
https://jsfiddle.net/lubber/vfb5zc47/4/

 The overall js head size does not increase in time (not even reaching more than 50MB and i ran it for a couple of minutes) when all toast are hidden.

![image](https://user-images.githubusercontent.com/18379884/219954355-dd0358b1-9a62-46f7-ad34-01d740a88458.png)

I adidtionally checked the following
- all created events are destroyed when the toasts are hidden
- also the DOM node is removed.
- setInterval is only used on debug:true and performance: true (and even then the heap size does not increase for me)
- used transition module does not bind events which need to be unbound
- progressbar does not use progress.js

Please adjust the jsfiddle so we are able to reproduce your described behavior.

**Comment by luki009** [comment] 2023-02-21 23:35
So I did play with JsFiddle and looks like problem is combination of  Jquery 3.1.1 and /fomantic-ui/2.9.1/semantic.min.js

<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.1/semantic.min.js"></script>

after those 2 are included in memory heap is rising 

![image](https://user-images.githubusercontent.com/8204290/220482756-73216b28-319e-484a-bf5e-9e068d31b29b.png)

**Comment by lubber-de** [comment] 2023-02-22 06:47
Thanks. It's a bug in jquery 3.1.1 until 3.2.1 it seems.
When starting to use jquery 3.3.0+ the leak seems to be gone.

Closing, because there is nothing to be done inside FUI.

**Closed by lubber-de** 2023-02-22 06:47 UTC
Labels: state/cannot-reproduce, needs-more-info
