### ISSUE TITLE
Chrome 122 does not display modals with scrolling content correct

### ISSUE THREAD

**Issue by achimkoellner** [fomantic/Fomantic-UI#2987] opened 2024-02-04 04:03 UTC
# Bug Report
The (dimmed) left margin of the modal somehow continues in the modal iteself.
It does not happen if the modal's inner div is not set to scrolling

## Steps to reproduce
Use Chrom 121.0.6167.139, setup a modal (any size but not fullscreen), open the modal.
A white layer (that cannot be picked in the developer tools inspector) of the sam size as the left margin between the modal and the window covers the inside of the modal.

## Expected result
The content of the modal should be visible and accessible.
All other browsers display this without problems, only Chrome 121.0.6167.139 fails.

## Actual result
The content is partially invisible and overlayed by a ghost element. This might be a paint/rendering bug with Chrom 121.0.6167.139.

## Screenshot (if possible)
<img width="1785" alt="Bildschirmfoto 2024-02-01 um 18 20 25" src="https://github.com/fomantic/Fomantic-UI/assets/1608268/7df01b57-9b66-48c3-84de-75ec2a3450c4">

<img width="894" alt="Bildschirmfoto 2024-02-02 um 11 34 56" src="https://github.com/fomantic/Fomantic-UI/assets/1608268/773b5c83-b5c1-4bdb-951e-2d2a41657f7e">

## Version
2.9.2

**Comment by lubber-de** [comment] 2024-02-04 18:03
Please provide a jsfiddle with your code, as i unfortunately cannot reproduce this using latest chrome 123 canary and
the scrolling content example at https://fomantic-ui.com/modules/modal.html#scrolling-content

**Comment by lubber-de** [comment] 2024-03-02 18:19
Closing, as i suspect this a bug in chromium and no testcase was given nor response has taken place.
As we also were not able to reproduce (without a proper jsfiddle), i think this issue is solved by chromium nightly.
If not, please report at https://www.chromium.org/for-testers/bug-reporting-guidelines/

**Closed by lubber-de** 2024-03-02 18:19 UTC
Labels: state/cannot-reproduce, browser/chromium, state/awaiting-more-info
