### ISSUE TITLE
[Calendar]initialDate: new Date(2019,2,1) with output "March 1, 800"

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#614] opened 2019-04-03 18:47 UTC
# Bug Report

## Steps to reproduce
1.iam initial date calendar
2.output year not same input

## Expected result

<img width="791" alt="Jepretan Layar 2019-04-04 pukul 2 45 34 AM" src="https://user-images.githubusercontent.com/33564576/55504602-c35f0680-5683-11e9-9dff-28c8e06533ee.png">

## Actual result
<img width="793" alt="Jepretan Layar 2019-04-04 pukul 2 44 35 AM" src="https://user-images.githubusercontent.com/33564576/55504543-a75b6500-5683-11e9-93fc-1f680355e001.png">

## Screenshot (when possible)
![]()

## Version
2.7.4

**Comment by lubber-de** [comment] 2019-04-03 19:01
Fixed by #610 
See https://jsfiddle.net/sruafp7k/1/

**Comment by apple-idn** [comment] 2019-04-03 19:14
wow, your a man @lubber-de how can do that temporary, back to include calendar.js?

**Comment by lubber-de** [comment] 2019-04-03 19:49
The jsdelivr CDN supports to serve files out of a github branch directly. So the current dist files are still 2.7.4 but overridden by the calendar.js from the PR branch where the issue is fixed
![image](https://user-images.githubusercontent.com/18379884/55508448-36ec1e00-565a-11e9-9014-1d8a058491b9.png)

**Comment by BrunoJuchli** [comment] 2019-04-25 05:48
As another temporary workaround, until the next version is released, I believe converting the `Date` object to a string with `.toDateString()` works, too:

    initialDate = myDate.toDateString()

I'm actually not a professional JS developer - I'm unsure whether this is the right conversion method overload or if it will break depending on client locale.

**Closed** 2019-05-16 08:33 UTC
Labels: :bug: confirmed bug, lang: JavaScript :scroll:
