### ISSUE TITLE
[Dropdown] Search selection selects first item on close

### ISSUE THREAD

**Issue by larsbo** [fomantic/Fomantic-UI#1742] opened 2020-11-03 08:38 UTC
# Bug Report
If you open a searchable dropdown and don't choose any item but closing the dropdown (clicking outside / clicking the dropdown arrow / press ESC) the first item of the results will be selected.

## Steps to reproduce

1. Go to https://fomantic-ui.com/modules/dropdown.html#search-selection
2. Click on the selection dropdown with placeholder "Select Country"
3. Don't select an item
4. Close the dropdown

## Expected result
No selected value.

## Actual result
Afghanistan :-/

## Version

2.x.x

**Comment by prudho** [comment] 2020-11-03 13:07
It's not a bug but a design choice. Selection dropdown mean that the user has to select something. But hopefully, this behavior can be modified by using the parameter `forceSelection: false` on initialization.

**Comment by larsbo** [comment] 2020-11-03 14:32
Well, if this was design decision it was definitely the wrong decision. It makes no sense to change the selection of the user didn’t select anything.

> Selection dropdown mean that the user has to select something.
That’s not true. There are `clearable` selections for example.
If a user should select something it should be forced by a `required` attribute in my opinion.

**Comment by lubber-de** [comment] 2020-11-03 17:35
We can discuss to make `forceSelection:true` by default for 2.9 (because it's a breaking change), but it's not a bug to be fixed in 2.8 (because `forceSelection: true` fixes it already as @prudho pointed out).
I'll prepare a PR for that for 2.9 (it's up to the reviewers then :wink:)

While we are at it: I will also start a discussion thread what default settings are supposed to be changed for 2.9.

**Comment by larsbo** [comment] 2020-11-03 19:15
That sounds like a good plan, thank you @lubber-de !

**Comment by lubber-de** [comment] 2020-11-03 21:30
Prepared a PR for the discussed change at #1747

**Closed** 2022-10-10 04:46 UTC
Labels: lang/javascript, type/usage
