### ISSUE TITLE
[Dropdown] Inline clearable dropdown is not clearable

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#924] opened 2019-08-07 16:49 UTC
# Bug Report

## Steps to reproduce
1. Create inline dropdown
2. Initialize dropdown with `clearable: true` option
3. Can't clear selection

## Expected result
Should have a little "x" icon to clear

## Actual result
Does not

## Testcase
https://jsfiddle.net/tfmbgz3e/
(Taken directly from the docs [here](https://fomantic-ui.com/modules/dropdown.html#clearable))

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7832163/62641513-f7338c80-b900-11e9-8448-cf8240a8bbfc.png)

## Version
2.7.7

**Comment by stjosh** [comment] 2020-04-08 06:29
Seems to be caused by the `module.is.selection()` this line - this basically disables clearable for all non-select dropdowns:

https://github.com/fomantic/Fomantic-UI/blob/3f3045c09176875bd3db674c0874bc4b96d0d3f7/src/definitions/modules/dropdown.js#L343

I wonder why this has diverged so much from Semantic-UI, where the clearable implementation seems to be quite different (and simpler!) and it works very well in the Demo? See 

- https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js (search for clearable)
- https://semantic-ui.com/modules/dropdown.html#/examples (Clearable Demo right at the top)

Anyway, my humble attempts to get this working failed.

**Comment by GammaGames** [comment] 2020-11-24 23:28
I'm liking my own issue because I ran into it again 😤️

**Comment by lubber-de** [comment] 2020-12-21 12:56
Fixed by https://github.com/fomantic/Fomantic-UI/pull/1807

**Closed** 2021-06-24 17:17 UTC
Labels: lang/javascript, type/bug
