### ISSUE TITLE
Inverted input fields are not dark-theme friendly.

### ISSUE THREAD

**Issue by NorteX-dev** [fomantic/Fomantic-UI#1635] opened 2020-08-09 18:37 UTC
# Bug Report

## Steps to reproduce
1. Use the [inverted input](https://fomantic-ui.com/elements/input.html#inverted) field

## Expected result
The inverted input should appear dark.

## Actual result
The input is not dark, and even in the docs, it isn't. It only becomes dark-theme friendly after it is also transparent. Even though it might have a few changes to better fit the inverted theme, I would much prefer it to be a dark background.

## Screenshot
![Screnshot of the docs](https://user-images.githubusercontent.com/32877032/89739302-e96a9700-da7f-11ea-8755-44eb83f316ee.png)

## Version
2.8.6 Fomantic UI from cdnjs.cloudflare.com

**Comment by lubber-de** [comment] 2020-08-09 18:52
Duplicate of #158

**Closed** 2020-08-09 19:23 UTC
Labels: type/duplicate
