### ISSUE TITLE
[accordion] not working in Firefox 103

### ISSUE THREAD

**Issue by Chulp** [fomantic/Fomantic-UI#2418] opened 2022-08-06 10:39 UTC
# Bug Report

the accordion function does not work properly in firefox

## Steps to reproduce

1. just go to the  fomantic website using firefox https://fomantic-ui.com/modules/accordion.html
2. just go to one of the accordion examples
3. open and close the accordion drop down : first time works OK
4. second time the dropdown is not shown. 
5. the same occurs in other examples
6. other browsers seem to be OK

## Version

2.x.x

**Comment by lubber-de** [comment] 2022-08-06 11:30
Duplicate of #2412 and fixed by #2417

**Closed** 2022-10-10 06:12 UTC
Labels: type/bug, type/duplicate, browser/firefox
