### ISSUE TITLE
[scope] copyright icon size is wrong

### ISSUE THREAD

**Issue by lisandelacruz** [fomantic/Fomantic-UI#1434] opened 2020-04-23 15:36 UTC
# Bug Report

Copyright icon is bigger than expected. Notably visbible when you use it inside an element.

## Steps to reproduce

Very simple:

For example in a dropdown icon component,
<div class="ui fluid scrolling dropdown labeled basic icon button">

The icon fails:

<div class="item" data-value="copyright">
    <i class="grey registered grey icon"></i>
    Copyright
    </div>

## Expected result

If you use any other icon, for example a "registered", it works fine:

<div class="item" data-value="copyright">
    <i class="grey registered grey icon"></i>
    Copyright
    </div>

## Actual result

Copyright icon is bigger and it destroys the component shape.

## Version

2.8.4
<img width="211" alt="1" src="https://user-images.githubusercontent.com/23529997/80118596-01fd8280-855f-11ea-9e6d-bf810b5f79d4.PNG">
<img width="232" alt="2" src="https://user-images.githubusercontent.com/23529997/80118607-0629a000-855f-11ea-9ac0-43a6a904c8fb.PNG">

**Comment by lubber-de** [comment] 2020-04-23 17:25
Could you please provide a jsfiddle? Because both icons have the same size in general
See https://jsfiddle.net/6xyj4mop/
PLease adjust the jsfiddle so we can reproduce the behavior.Thanks! 🙂

**Comment by lubber-de** [comment] 2020-05-03 21:48
Closing because of no more response. If you still think this is a bug, please adjust the above mentioned [jsfiddle](https://jsfiddle.net/6xyj4mop/1/) accordingly

**Closed by lubber-de** 2020-05-03 21:48 UTC
Labels: state/awaiting-more-info, state/cannot-reproduce
