### ISSUE TITLE
[modal] Modal transition only works on first open on Chrome

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1458] opened 2020-05-10 18:37 UTC
# Bug Report
With Fomantic UI 2.8.4 on Chrome ...
When opening a modal the first time a page loads, it animates the transition correctly.
The second time, it just pops up, no animation.

![May-10-2020 14-21-10](https://user-images.githubusercontent.com/146623/81507236-f2ee3280-92c9-11ea-9ce4-8fe27b6bc767.gif)

I'm initiating the modal like so ...
```javascript
$('#address_modal')
    .modal({
        transition: 'horizontal flip',
        onApprove: function(){
            my_custom_function();
            return false;
        }
    });

$('#address_view .button').on('click', function(e){
    e.preventDefault();
    $('#address_modal .ui.error.message').empty();
    $('#address_modal').form('clear').modal('show');
});
```

This works fine in Firefox. I could swear this was working in Chrome not long ago, so it's possible some other code is interfering. I thought perhaps it might be an extension, but it does the same thing in Incognito mode (with no extensions). Has anyone experienced this? Or am I calling my modals incorrectly?

**Comment by lubber-de** [comment] 2020-05-10 19:10
I cannot reproduce this in a simple modal call using chrome
See https://jsfiddle.net/s9eya5rg/

![modaltransition](https://user-images.githubusercontent.com/18379884/81508159-b68af880-9302-11ea-9516-1f988053d401.gif)


**Please adjust the jsfiddle, so we can reproduce the behavior.**

It seems weird, that you use a form as a modal as well. I believe this is a reason for this.
We had a similar behavior before when a modal should be shown when a previous transition was not completed.

**Comment by neokio** [comment] 2020-05-10 21:50
I spent about an hour trying to reproduce the problem on jsfiddle, but was unable to do so.
Maybe it's related to the google places API lookup?
I'll see if I can narrow it down more later.
Thanks for helping me look!

**Comment by neokio** [comment] 2020-05-10 21:59
Yep, that was it. Modals containing an input that's bound to google.maps.places.Autocomplete somehow breaks the modal on second load. The input works fine on both the first and subsequence modals, just that animation, even though the parent is never touched by js, only that one input.

**Comment by lubber-de** [comment] 2020-05-12 16:11
I was able to reproduce now. Google places api sets another css class to the input field which adds an animation name which in turn prevents the modal to be animated. To fix this for you, add
```
.pac-target-input {
  animation-name: none !important;
}
```
See https://jsfiddle.net/enhyb64j/1/

I am closing this, because it's not related to FUI and a workaround is given

**Closed by lubber-de** 2020-05-12 16:11 UTC
Labels: browser/chromium, needs-more-info, state/awaiting-investigation, state/awaiting-response, state/cannot-reproduce
