### ISSUE TITLE
Search Selection Dropdown does not fully work on Mobile

### ISSUE THREAD

**Issue by douglas-gf** [fomantic/Fomantic-UI#2271] opened 2022-03-18 09:43 UTC
# Bug Report

## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/dropdown.html#/definition
2. Go to the "Search Selection" section 
3. Ctrl + Shift + J to enter chrome inspector
4. Ctrl + Shift + M to Toggle Device Toolbar
5. Refresh the page
6. Click on the Search Selection dropdown
7. No dropdown will appear unless a value is entered.

## Expected result
The dropdown will appear when it is being tapped on.
![image](https://user-images.githubusercontent.com/101865939/158975501-874a86f5-08b3-44be-8671-60581e8896ac.png)

## Actual result
The dropdown does not appear unless a value is entered.
![image](https://user-images.githubusercontent.com/101865939/158975376-15dffe6c-b5b5-4299-b3aa-fcfee51559d3.png)

## Testcase
No test case as the issue is in the fomantic UI website.

## Screenshot (when possible)
I have provided the screenshots above in the results.

## Version
2.8

**Comment by lubber-de** [comment] 2022-03-18 13:48
Duplicate of #2176

**Comment by lubber-de** [comment] 2022-08-03 18:02
Fixed by #2414 See  https://fomantic-ui.com/jsfiddle/#!lubber/qmedoujL/3/

**Closed** 2022-10-10 05:50 UTC
Labels: type/bug, type/duplicate
