### ISSUE TITLE
[Calendar] End date in a range not updated when you edit begin date with a date after current date

### ISSUE THREAD

**Issue by hbooo** [fomantic/Fomantic-UI#1929] opened 2021-03-26 13:57 UTC
# Bug Report
End date in a range not updated when you edit begin date with a date after current date

## Steps to reproduce
1. Go to [Calendar page, range section](https://fomantic-ui.com/modules/calendar.html#range) 
2. Select a start date, click on a day
3. End date calendar is opened
4. Close the calendar and modify the begin date with keyboard and set 2023 in the year part
5. Validate with entry
6. End date is opened with year 2021 and user is unable to use arrows to change date

## Expected result
Year should be updated in end date and arrows should work to select a date

## Actual result
Year is not updated and arrows doesn't work to select a date

## Testcase
https://fomantic-ui.com/modules/calendar.html#range

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/242125/112641810-01423000-8e43-11eb-9d30-64313e9f574f.png)

## Version
2.8

**Comment by lubber-de** [comment] 2021-03-26 14:18
Duplicate of #1364 and #1851

**Closed by lubber-de** 2021-03-26 14:18 UTC
Labels: state/awaiting-investigation, state/awaiting-triage, type/bug
