### ISSUE TITLE
[modal] Dimmer not removed when clicking on close icon

### ISSUE THREAD

**Issue by iamareebjamal** [fomantic/Fomantic-UI#1590] opened 2020-07-17 01:23 UTC
In fomantic UI, the level and place in which the modal is rendered creates a bug where clicking on close icon does not remove the dimmer. If the same model is placed somewhere else, it works as expected. This is a regression from semantic UI where it works correctly regardless of the location of rendering.

Semantic UI example:

https://eventyay.com/e/16fa59c7

1. Choose 1 ticket and click order. Popup opens up
2. Click on cross icon on the popup
3. Popup closes and dimmer is removed as well

Fomantic UI with no code changes, drop in replacement, dimmer is not removed. Working on creating a reproduction link but `yarn install` does not work for fomantic, another blocking regression from semantic mentioned here from 1 year ago - #811

**Comment by lubber-de** [comment] 2020-07-17 08:46
First: Please create a jsfiddle out of your code, because we don't have time to inspect your whole website to guess and find out what is different in your codebase in might be responsible for your issue. Thank you 🙂 

I spent some minutes on your website and as far as i can see, it seems you have added the `legacy` class manually which is basically not necessary when not using Internet Explorer.
It also seems you are using ember which is creating the html code automatically for you.

However, i copied the modal html code from your website so far and  used that to prepare a small jsfiddle with default FUI code, which shows, that the dimmer is removed just fine as it should.

### Please adjust the following working jsfiddle so we can reproduce your issue
See https://jsfiddle.net/lubber/z46dpwst/7/

![modaldimmer](https://user-images.githubusercontent.com/18379884/87766773-f813b480-c819-11ea-93b1-074d6bd9d192.gif)


#### Regarding `yarn`
yarn might work for sui, but sui does not work with newer node and gulp 4 versions instead.
Please continue discussion about yarn in a separate thread and let's focus on the dimmer/modal issue here.

 Anyway, we already seek for volunteer helpers on yarn, so if you are interested in helping out for the yarn issue, you are welcome to provide a PR 😉

**Comment by iamareebjamal** [comment] 2020-07-17 15:04
Yes my first goal was to create a reproduction issue but as you can see it is a conditional issue which happens with a lot of nesting and isn't exactly clear why and where it happens, it is very difficult to reproduce from a new repo. This may actually be happening due to some incompatibilities with ember or other package, which isn't necessarily a fault in fomantic UI but is a regression anyway. However, I'll try to debug and find why exactly it happens and reproduce the case but I unfortunately, don't have too much free time as well. Will see how much I can allocate.

**Comment by lubber-de** [comment] 2020-07-29 12:45
Closing for now. Will reopen when you could provide a reproducable jsfiddle testcase

**Closed by lubber-de** 2020-07-29 12:45 UTC
Labels: state/awaiting-more-info, state/cannot-reproduce

**Comment by h0lg** [comment] 2023-09-11 12:37
> ### Please adjust the following working jsfiddle so we can reproduce your issue
> See https://jsfiddle.net/lubber/z46dpwst/7/

@lubber-de I was able to modify your fiddle to reproduce the issue. Please see https://jsfiddle.net/0ecLmbrj/
