### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by walletcrea** [fomantic/Fomantic-UI#588] opened 2019-03-25 13:09 UTC
### ` <div class="ui dropdown">
       <div class="text">File</div>
       <i class="dropdown icon"></i>
       <div class="menu">
           <div class="item">New</div>
           <div class="item">
               <span class="description">ctrl + o</span>
               Open...
           </div>
           <div class="item">
               <span class="description">ctrl + s</span>
               Save as...
           </div>
           <div class="item">
               <span class="description">ctrl + r</span>
               Rename
           </div>
           <div class="item">Make a copy</div>
           <div class="item">
               <i class="folder icon"></i>
               Move to folder
           </div>
           <div class="item">
               <i class="trash icon"></i>
               Move to trash
           </div>
           <div class="divider"></div>
           <div class="item">Download As...</div>
           <div class="item">
               <i class="dropdown icon"></i>
               Publish To Web
               <div class="menu">
                   <div class="item">Google Docs</div>
                   <div class="item">Google Drive</div>
                   <div class="item">Dropbox</div>
                   <div class="item">Adobe Creative Cloud</div>
                   <div class="item">Private FTP</div>
                   <div class="item">Another Service...</div>
               </div>
           </div>
           <div class="item">E-mail Collaborators</div>
       </div>
   </div>`

**Comment by lubber-de** [comment] 2019-03-25 13:26
@walletcrea
- You have to wrap your code into
```html
<div class="ui dropdown"
 <!-- your above code -->
</div>
```
- Call the dropdown by `$('.ui.dropdown').dropdown()`
- Don't forget to include jquery

See fiddle here: https://jsfiddle.net/9451gpd6/

**Comment by walletcrea** [comment] 2019-03-25 15:25
<ul>
<Li>it doesnt work either.Am using the cdnjs</li>
</ul>
<code style="color:red;"> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script><br>

      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.2/semantic.min.css"><br>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.2/semantic.min.js"></script>
</code>

<ul>
<li style='list-style-type:square'>And my code is</li>
</ul>

```HTML
<div class="ui dropdown">
       <div class="text">File</div>
       <i class="dropdown icon"></i>
       <div class="menu">
           <div class="item">New</div>
           <div class="item">
               <span class="description">ctrl + o</span>
               Open...
           </div>
           <div class="item">
               <span class="description">ctrl + s</span>
               Save as...
           </div>
           <div class="item">
               <span class="description">ctrl + r</span>
               Rename
           </div>
           <div class="item">Make a copy</div>
           <div class="item">
               <i class="folder icon"></i>
               Move to folder
           </div>
           <div class="item">
               <i class="trash icon"></i>
               Move to trash
           </div>
           <div class="divider"></div>
           <div class="item">Download As...</div>
           <div class="item">
               <i class="dropdown icon"></i>
               Publish To Web
               <div class="menu">
                   <div class="item">Google Docs</div>
                   <div class="item">Google Drive</div>
                   <div class="item">Dropbox</div>
                   <div class="item">Adobe Creative Cloud</div>
                   <div class="item">Private FTP</div>
                   <div class="item">Another Service...</div>
               </div>
           </div>
           <div class="item">E-mail Collaborators</div>
       </div>
   </div>
```

**Comment by walletcrea** [comment] 2019-03-25 15:38
- doesnt work neither,am using cdnjs
```HTML
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.2/semantic.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.2/semantic.min.js"></script>
```

- and my code is
```HTML
<div class="ui dropdown">
       <div class="text">File</div>
       <i class="dropdown icon"></i>
       <div class="menu">
           <div class="item">New</div>
           <div class="item">
               <span class="description">ctrl + o</span>
               Open...
           </div>
           <div class="item">
               <span class="description">ctrl + s</span>
               Save as...
           </div>
           <div class="item">
               <span class="description">ctrl + r</span>
               Rename
           </div>
           <div class="item">Make a copy</div>
           <div class="item">
               <i class="folder icon"></i>
               Move to folder
           </div>
           <div class="item">
               <i class="trash icon"></i>
               Move to trash
           </div>
           <div class="divider"></div>
           <div class="item">Download As...</div>
           <div class="item">
               <i class="dropdown icon"></i>
               Publish To Web
               <div class="menu">
                   <div class="item">Google Docs</div>
                   <div class="item">Google Drive</div>
                   <div class="item">Dropbox</div>
                   <div class="item">Adobe Creative Cloud</div>
                   <div class="item">Private FTP</div>
                   <div class="item">Another Service...</div>
               </div>
           </div>
           <div class="item">E-mail Collaborators</div>
       </div>
   </div>
```

**Comment by lubber-de** [comment] 2019-03-25 16:41
Works fine with the given CDN links
See https://jsfiddle.net/3f8tnxwy/

Did you implement `$('.ui.dropdown').dropdown()` ?

**Comment by walletcrea** [comment] 2019-03-25 17:01
It works fine on jsfiddle and codepen,,, but it doesnt work on my laptop,,,, i have also implemented`$('.ui.dropdown').dropdown()` in an external js and also included it in my html

**Comment by lubber-de** [comment] 2019-03-25 17:02
Is the external JS file included __after__ jquery and fomantic has been included? (also without 'async')?
What does the console output say? Any error hints?

**Comment by lubber-de** [comment] 2019-03-25 17:05
Are you using a local webserver or just calling a local html file? (Then remote links to all external cdn files  are most probably not loaded)

**Comment by walletcrea** [comment] 2019-03-26 07:52
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

> Are you using a local webserver or just calling a local html file? (Then remote links to all external cdn files are most probably not loaded)

- am using express listening on port 3000

**Comment by walletcrea** [comment] 2019-03-26 07:54
> Is the external JS file included **after** jquery and fomantic has been included? (also without 'async')?
> What does the console output say? Any error hints?

1. yes its included after jquery and formantic and without async

**Comment by lubber-de** [comment] 2019-03-26 07:56
What did the console output say when you instantiate the dropdown? Sorry, but without a reproducable fiddle we cannot get anything fixed in the framework, if the issue is related to your environment only

**Comment by walletcrea** [comment] 2019-03-26 10:55
_**thanks**_ @lubber-de  but i found a way around it,,,,all i had to do is put the `<scripts>` at the end near the `</body>` tag
```html
 <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.2/dist/semantic.min.js"></script>
   <script src="/javascripts/style.js"></script>

  </body>
```

- and the stylesheet with formantic at the `<head>`tag
```html
 <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.2/dist/semantic.min.css">
```

**Closed** 2019-03-26 10:58 UTC
Labels: :thinking: cannot reproduce, :thought_balloon: usage question
