### ISSUE TITLE
[Dropdown] module.is.chrome() is returning false when should be true

### ISSUE THREAD

**Issue by timbit123** [fomantic/Fomantic-UI#2203] opened 2022-01-17 16:43 UTC
# Bug Report
this line: https://github.com/fomantic/Fomantic-UI/blob/31d0f3ffde8f10b294ab2a81dc5d2e70ab76ecc4/src/definitions/modules/dropdown.js#L3400

module.is.chrome return false because window.chrome.webstore and window.chrome.runtime doesn't exist (anymore?)
Im on Chrome Version 97.0.4692.71

## Steps to reproduce
1. create a tag with `<div class="ui fluid search selection dropdown">`
2. run in chrome
3.

## Expected result
result should be autocomplete="fomantic-search"

## Actual result
because is.chrome isn't detected. autocomplete is set to "off" and display the chrome autocomplete

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/1305508/149808087-4f4fe410-ad75-4726-9d5e-8e2d3cdb4c9f.png)
![image](https://user-images.githubusercontent.com/1305508/149808004-8d7f4f19-7f75-415a-b401-2a27e7d19683.png)

## Version

2.9.0-beta.162

Thank you!

**Comment by lubber-de** [comment] 2022-01-17 16:54
mmh, cannot reproduce at the moment. I am on windows, same chrome version, the mentioned `is.chrome` method returns true

![image](https://user-images.githubusercontent.com/18379884/149810125-24b2f669-47dd-4ab8-8228-42b8bc2c2bf1.png)

**Comment by lubber-de** [comment] 2022-01-17 17:00
mmh, are you testing using inkognito mode?
because it seems the `window.chrome.runtime` does exist in normal mode, but is not available in inkognito mode
#### Normal
![image](https://user-images.githubusercontent.com/18379884/149810551-bd42ca8a-e7c4-4a3d-8571-c5430ade9e6a.png)
#### Inkognito
![image](https://user-images.githubusercontent.com/18379884/149810919-f1524391-1836-4923-8559-d5f665b528a0.png)

i'll investigate how to improve that

**Comment by lubber-de** [comment] 2022-01-17 17:28
Fixed by #2204 
It affects all chromium based browser, so i simply removed the additional checks as `!!window.chrome` is sufficient

**Comment by timbit123** [comment] 2022-01-17 17:58
I am on arm64 version (mac m1) and not in incognito. I will double check on other OS

**Comment by timbit123** [comment] 2022-01-17 18:13
I think runtime isn't available with http:// only https://
I guess that's why it doesn't work when developing locally

**Closed** 2022-10-10 05:36 UTC
Labels: type/bug, browser/chromium
