### ISSUE TITLE
[Modal] onApprove cannot prevent hiding when modal is created with JS API.

### ISSUE THREAD

**Issue by hdogan** [fomantic/Fomantic-UI#2105] opened 2021-09-16 14:28 UTC
# Bug Report
As per documentation (and module code), if `onApprove` callback returns `false` then modal should not be hidden on clicking approval button. But it still hides.

`onApprove` return value checked in: https://github.com/fomantic/Fomantic-UI/blob/e39a0ae5183c12808ba1eee82082efbb15f4d450/src/definitions/modules/modal.js#L322

## Steps to reproduce
1. Create modal with JS API
2. Show modal
3. Click approval button

## Expected result
Modal should not be hide.

## Actual result
Modal hides.

## Testcase
https://jsfiddle.net/pbcr1qL5/5/

## Version
2.8.8

**Comment by hdogan** [comment] 2021-09-16 20:35
Here are the chain of debug logs when I click approval button.

Debug outputs `Approval callback returned false cancelling hide` message but it continues hiding process.

![fomantic-ui-modal-onapprove-bug](https://user-images.githubusercontent.com/777820/133681938-61c5ce73-ad02-4fd5-a947-3d7898acdfec.png)

**Comment by lubber-de** [comment] 2021-09-16 21:15
Confirmed. Also happens with `onDeny` 

### Reason explained
Actions provided via JS paramater do have a default click handler to hide the modal if no click handler if given or, if given, returns false.

The `onApprove` event in this case is triggered additionally, because this was originally invented to auto attach events to pre-existing action buttons in a modal already created in the DOM tree.

So, your buttons have actually 2 handlers, the onapprove was indeed not hiding the modal, but the automatically created button trigger was (because you did not provide a click handler for the action button.

We will create a fix for this.

### In the meantime you can use one of the following workarounds

a) Change the color from `positive` to `green` and use a click handler instead ot the onApprove callback
https://jsfiddle.net/lubber/np2bdLew/7/

b) Add a click handler to your `positive` action which returns false and still use the `onapprove` callback
https://jsfiddle.net/lubber/np2bdLew/6/

c) Keep your `positive` class, but set the internal selector for approve buttons to something not existing like a space string
https://jsfiddle.net/lubber/np2bdLew/10/

**Comment by hdogan** [comment] 2021-09-16 21:21
Maybe related issue on Semantic UI repo: https://github.com/Semantic-Org/Semantic-UI/issues/3524

**Comment by hdogan** [comment] 2021-09-17 07:08
https://github.com/fomantic/Fomantic-UI/blob/e8e7ca4f21095bcf663394c56d988ace44740101/src/definitions/modules/modal.js#L129-L134

I'm not a JS guy but will checking with these conditions in `click` handler be enough?

```js
if (element.is(selector.approve) && $.isFunction(settings.onApprove)) {
    return;
}

if (element.is(selector.deny) && $.isFunction(settings.onDeny)) {
    return;
}
```

**Comment by lubber-de** [comment] 2021-09-17 07:15
Yes, you are basically on the right track 🙂
However "onApprove" is always a function by default and `element` is the whole modal.

**Comment by lubber-de** [comment] 2021-09-17 08:03
Fixed by #2108

**Comment by hdogan** [comment] 2021-09-17 08:07
Ops, you're right. And I've just noticed that buttons are dynamically created with registering click handler set (jQuery magic) and appended to actions div.

I've stopped assuming a solution with only reading code and tested with that code this time:

```js
click: function (event) {
  if (click.call(element, $module) === false) {
    return;
  }

  if ($(event.target).is(selector.approve + ', ' + selector.deny)) {
      module.verbose('Preventing default click action on approving/denying action');
      return;
  }

  module.hide();
}
```

**Comment by hdogan** [comment] 2021-09-17 08:08
Ops just noticed your PR 🥳

**Comment by lubber-de** [comment] 2021-09-17 08:29
I added appropriate infos to the docs by https://github.com/fomantic/Fomantic-UI-Docs/pull/311

**Closed** 2022-10-10 05:19 UTC
Labels: type/bug, lang/javascript
